apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: webhook-flux-kfirs-com
  namespace: flux-system
spec:
  secretName: webhook-flux-kfirs-com-tls
  issuerRef:
    kind: ClusterIssuer
    name: google-clouddns
  dnsNames:
    - webhook.flux.${gke_cluster_name}.kfirs.com
