apiVersion: notification.toolkit.fluxcd.io/v1
kind: Receiver
metadata:
  name: delivery
  namespace: flux-system
spec:
  type: github
  events:
    - "ping"
    - "push"
  secretRef:
    name: fluxcd-github-webhook-secret
  resources:
    - kind: GitRepository
      name: flux-system
      namespace: flux-system
    - kind: GitRepository
      name: greenstar
      namespace: fix-main-branch-deployment
    - kind: GitRepository
      name: greenstar
      namespace: dependabot-go-module-ors-1-10-1
    - kind: GitRepository
      name: greenstar
      namespace: dependabot-go-module-dis-1-0-19
    - kind: GitRepository
      name: greenstar
      namespace: dependabot-npm-and-y-rser-6-7-3
    - kind: GitRepository
      name: greenstar
      namespace: dependabot-npm-and-y-em-5-14-11
