apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: fluxcd-github-webhook-secret
  namespace: flux-system
spec:
  refreshInterval: 30m
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-manager
  data:
    - secretKey: token
      remoteRef:
        key: fluxcd-github-webhook-secret
