apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: notification-controller-gcpsm
  namespace: flux-system
spec:
  provider:
    gcpsm:
      projectID: arikkfir
      auth:
        workloadIdentity:
          clusterLocation: me-west1-a
          clusterName: main
          serviceAccountRef:
            name: notification-controller
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: fluxcd-github-webhook-secret
  namespace: flux-system
spec:
  refreshInterval: 30m
  secretStoreRef:
    kind: SecretStore
    name: notification-controller-gcpsm
  data:
    - secretKey: token
      remoteRef:
        key: fluxcd-github-webhook-secret
