apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Alert
metadata:
  name: echo-server
spec:
  providerRef:
    name: github-delivery
  summary: Alert
  eventSeverity: info
  eventSources:
    - kind: Kustomization
      name: echo-server
---
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Alert
metadata:
  name: greenstar
spec:
  providerRef:
    name: github-greenstar
  summary: Alert
  eventSeverity: info
  eventSources:
    - kind: Kustomization
      name: greenstar
