apiVersion: notification.toolkit.fluxcd.io/v1
kind: Receiver
metadata:
  name: delivery
spec:
  type: github
  events:
    - "ping"
    - "push"
  secretRef:
    name: fluxcd-github-webhook-secret
  resources:
    - kind: GitRepository
      name: echo-server
    - kind: GitRepository
      name: greenstar
