apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: greenstar
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: flux-github-token
  url: https://github.com/arikkfir/greenstar
