apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: echo-server
spec:
  interval: 5m0s
  ref:
    branch: main
  secretRef:
    name: flux-github-token
  url: https://github.com/arikkfir/delivery
