apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: echo-server
spec:
  force: true
  interval: 10m
  path: /apps/echo-server
  patches:
    # Main environment should use the ACME PRODUCTION server for browsers to trust this environment
    - target:
        group: cert-manager.io
        version: v1
        kind: Certificate
      patch: |-
        - op: replace
          path: /spec/issuerRef/name
          value: google-clouddns-prod
  postBuild:
    substitute:
      deploy_environment: main
  prune: true
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: echo-server
  targetNamespace: main
  timeout: 5m
  wait: true
