apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: greenstar
spec:
  force: true
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: greenstar-redis
      namespace: main
    - apiVersion: apps/v1
      kind: Deployment
      name: greenstar-neo4j
      namespace: main
    - apiVersion: apps/v1
      kind: Deployment
      name: greenstar-api-backend
      namespace: main
    - apiVersion: apps/v1
      kind: Deployment
      name: greenstar-frontend
      namespace: main
    - apiVersion: dns.cnrm.cloud.google.com/v1beta1
      kind: DNSRecordSet
      name: greenstar-wildcard-cname-record
      namespace: main
    - apiVersion: cert-manager.io/v1
      kind: Certificate
      name: greenstar-wildcard
      namespace: main
  interval: 1m
  path: /deploy
  patches:
    # Main environment should use the ACME PRODUCTION server for browsers to trust this environment
    - target:
        group: cert-manager.io
        version: v1
        kind: Certificate
      patch: |-
        - op: replace
          path: /spec/issuerRef/name
          value: google-clouddns-prod
  postBuild:
    substitute:
      deploy_environment: main
  prune: true
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: greenstar
  targetNamespace: main
  timeout: 5m
