apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ${flux_environment}
resources:
  - ../../apps/echo-server
  - ../../apps/greenstar
patches:
  - target:
      group: cert-manager.io
      version: v1
      kind: Certificate
    patch: |-
      - op: replace
        path: /spec/issuerRef/name
        value: google-clouddns-prod
