apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: main
images:
  - name: ghcr.io/arikkfir/greenstar/backend
    newTag: 4fb624c1140a2aba187cecc26570d139173185cb
  - name: ghcr.io/arikkfir/greenstar/frontend
    newTag: 4fb624c1140a2aba187cecc26570d139173185cb
  - name: ghcr.io/arikkfir/greenstar/migrations
    newTag: 4fb624c1140a2aba187cecc26570d139173185cb
  - name: ghcr.io/arikkfir/greenstar/neo4j
    newTag: 4fb624c1140a2aba187cecc26570d139173185cb
resources:
  - ../../apps/echo-server
  - ../../apps/greenstar
patches:
  - target:
      group: cert-manager.io
      version: v1
      kind: Certificate
    patch: |-
      - op: replace
        path: /spec/issuerRef/name
        value: google-clouddns-prod
