apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ${flux_environment}
resources:
  - namespace.yaml
  - echo-server.yaml
  - https://github.com/arikkfir/greenstar//deploy/cluster?ref=${flux_environment}
