apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: greenstar
spec:
  force: true
  healthChecks:
    - apiVersion: iam.cnrm.cloud.google.com/v1beta1
      kind: IAMServiceAccount
      name: greenstar-secrets
    - apiVersion: iam.cnrm.cloud.google.com/v1beta1
      kind: IAMPolicyMember
      name: greenstar-secrets-ksa-link
    - apiVersion: iam.cnrm.cloud.google.com/v1beta1
      kind: IAMPolicyMember
      name: greenstar-secrets-secret-viewer
    - apiVersion: iam.cnrm.cloud.google.com/v1beta1
      kind: IAMPolicyMember
      name: greenstar-secrets-secret-accessor
    - apiVersion: external-secrets.io/v1beta1
      kind: SecretStore
      name: greenstar-gcp
    - apiVersion: v1
      kind: PersistentVolumeClaim
      name: greenstar-redis
    - apiVersion: apps/v1
      kind: Deployment
      name: greenstar-redis
  interval: 5m
  path: /
  postBuild:
    substitute:
      deploy_branch: main
      deploy_environment: main
  prune: true
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: greenstar
  targetNamespace: main
  timeout: 5m
