apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: main
images:
  - name: ghcr.io/arikkfir/greenstar/backend
    newTag: e06fb26a6439e5ced0a6c27e7900407aec219d07
  - name: ghcr.io/arikkfir/greenstar/frontend
    newTag: e06fb26a6439e5ced0a6c27e7900407aec219d07
  - name: ghcr.io/arikkfir/greenstar/migrations
    newTag: e06fb26a6439e5ced0a6c27e7900407aec219d07
  - name: ghcr.io/arikkfir/greenstar/neo4j
    newTag: e06fb26a6439e5ced0a6c27e7900407aec219d07
resources:
  - ../../apps/echo-server
  - ../../apps/greenstar
patches:
  - target:
      group: cert-manager.io
      version: v1
      kind: Certificate
    patch: |-
      - op: replace
        path: /spec/issuerRef/name
        value: google-clouddns-prod
