apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: main
resources:
  - namespace.yaml
  - secret-github-token.yaml
  - gitrepository-echo-server.yaml
  - kustomization-echo-server.yaml
  - gitrepository-greenstar.yaml
  - kustomization-greenstar.yaml
