apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: greenstar
spec:
  force: true
  healthChecks:
    - apiVersion: iam.cnrm.cloud.google.com/v1beta1
      kind: IAMServiceAccount
      name: greenstar-secrets
      namespace: main
    - apiVersion: iam.cnrm.cloud.google.com/v1beta1
      kind: IAMPolicyMember
      name: greenstar-secrets-ksa-link
      namespace: main
    - apiVersion: iam.cnrm.cloud.google.com/v1beta1
      kind: IAMPolicyMember
      name: greenstar-secrets-secret-viewer
      namespace: main
    - apiVersion: iam.cnrm.cloud.google.com/v1beta1
      kind: IAMPolicyMember
      name: greenstar-secrets-secret-accessor
      namespace: main
    - apiVersion: external-secrets.io/v1beta1
      kind: SecretStore
      name: greenstar-gcp
      namespace: main
    - apiVersion: v1
      kind: PersistentVolumeClaim
      name: greenstar-redis
      namespace: main
    - apiVersion: apps/v1
      kind: Deployment
      name: greenstar-redis
      namespace: main
  interval: 5m
  path: /
  patches:
    # Main environment should use the ACME PRODUCTION server for browsers to trust this environment
    - target:
        group: cert-manager.io
        version: v1
        kind: Certificate
      patch: |-
        - op: replace
          path: /spec/issuerRef/name
          value: google-clouddns-prod
  postBuild:
    substitute:
      deploy_branch: main
      deploy_environment: main
  prune: true
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: greenstar
  targetNamespace: main
  timeout: 5m
