apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: echo-server
spec:
  force: true
  healthChecks:
    - apiVersion: cert-manager.io/v1
      kind: Certificate
      name: echo-server-root
    - apiVersion: dns.cnrm.cloud.google.com/v1beta1
      kind: DNSRecordSet
      name: echo-server-a-record
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: echo-server-echo-server
  interval: 5m
  path: /apps/echo-server
  patches:
    # Main environment should use the ACME PRODUCTION server for browsers to trust this environment
    - target:
        group: cert-manager.io
        version: v1
        kind: Certificate
      patch: |-
        - op: replace
          path: /spec/issuerRef/name
          value: google-clouddns-prod
  postBuild:
    substitute:
      deploy_branch: main
      deploy_environment: main
  prune: true
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: echo-server
  targetNamespace: main
  timeout: 5m
