apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: greenstar
spec:
  force: true
  healthChecks:
    - apiVersion: iam.cnrm.cloud.google.com/v1beta1
      kind: IAMServiceAccount
      name: greenstar-secrets
  interval: 5m
  path: /
  postBuild:
    substitute:
      deploy_branch: main
      deploy_environment: main
  prune: true
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: greenstar
  timeout: 5m
