apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: add-greenstar-word-to-dns-record
resources:
  - ../_commons/namespace.yaml
  - ../_commons/echo-server.yaml
  - https://github.com/arikkfir/greenstar//deploy/cluster?ref=add-greenstar-word-to-dns-record
