apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: github-head_ref
resources:
  - ../_commons/namespace.yaml
  - ../_commons/echo-server.yaml
  - https://github.com/arikkfir/greenstar//deploy/cluster?ref=github.head_ref
