apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  interval: 5m
  chart:
    spec:
      chart: external-secrets
      sourceRef:
        kind: HelmRepository
        name: external-secrets
  values:
    installCRDs: true
    crds:
      createClusterExternalSecret: true
      createClusterSecretStore: true
    concurrent: 1
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 128Mi
    nodeSelector:
      node.kfirs.com/role: work
    tolerations:
      - effect: NoExecute
        key: node.kfirs.com/role
        operator: Equal
        value: work
    webhook:
      nodeSelector:
        node.kfirs.com/role: work
      tolerations:
        - effect: NoExecute
          key: node.kfirs.com/role
          operator: Equal
          value: work
      resources:
        requests:
          cpu: 50m
          memory: 32Mi
        limits:
          cpu: 200m
          memory: 64Mi
    certController:
      nodeSelector:
        node.kfirs.com/role: work
      tolerations:
        - effect: NoExecute
          key: node.kfirs.com/role
          operator: Equal
          value: work
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 200m
          memory: 128Mi

  # This prevents "reconciliation failed: install retries exhausted" errors
  install:
    disableWait: true
  upgrade:
    disableWait: true
