apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: external-secrets
spec:
  interval: 5m
  url: https://charts.external-secrets.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-secrets
spec:
  interval: 5m
  timeout: 5m
  chart:
    spec:
      chart: external-secrets
      sourceRef:
        kind: HelmRepository
        name: external-secrets
  values:
    installCRDs: true
    crds:
      createClusterExternalSecret: true
      createClusterSecretStore: true
    concurrent: 1
    serviceAccount:
      annotations: { }
    resources:
      requests:
        cpu: 50m
        memory: 32Mi
      limits:
        cpu: 200m
        memory: 64Mi
    nodeSelector:
      gke.kfirs.com/purpose: workloads
    tolerations:
      - effect: NoExecute
        key: gke.kfirs.com/purpose
        operator: Equal
        value: workloads
    webhook:
      nodeSelector:
        gke.kfirs.com/purpose: workloads
      tolerations:
        - effect: NoExecute
          key: gke.kfirs.com/purpose
          operator: Equal
          value: workloads
      resources:
        requests:
          cpu: 50m
          memory: 32Mi
        limits:
          cpu: 200m
          memory: 64Mi
    certController:
      nodeSelector:
        gke.kfirs.com/purpose: workloads
      tolerations:
        - effect: NoExecute
          key: gke.kfirs.com/purpose
          operator: Equal
          value: workloads
      resources:
        requests:
          cpu: 50m
          memory: 32Mi
        limits:
          cpu: 200m
          memory: 64Mi
