apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: arikkfir-merge-branch-and-pr-workflows
images:
  - name: ghcr.io/arikkfir/greenstar/backend
    newTag: 70a5a6f42633f8abd3bec05ece1539e2abbeb4d5
  - name: ghcr.io/arikkfir/greenstar/frontend
    newTag: 70a5a6f42633f8abd3bec05ece1539e2abbeb4d5
  - name: ghcr.io/arikkfir/greenstar/migrations
    newTag: 70a5a6f42633f8abd3bec05ece1539e2abbeb4d5
  - name: ghcr.io/arikkfir/greenstar/neo4j
    newTag: 70a5a6f42633f8abd3bec05ece1539e2abbeb4d5
patches: []
resources:
  - ../main
