apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: arikkfir-merge-branch-and-pr-workflows
images:
  - name: ghcr.io/arikkfir/greenstar/backend
    newTag: dbea1370b6be8e7a3c37b3d34f4a676a1e484efe
  - name: ghcr.io/arikkfir/greenstar/frontend
    newTag: dbea1370b6be8e7a3c37b3d34f4a676a1e484efe
  - name: ghcr.io/arikkfir/greenstar/migrations
    newTag: dbea1370b6be8e7a3c37b3d34f4a676a1e484efe
  - name: ghcr.io/arikkfir/greenstar/neo4j
    newTag: dbea1370b6be8e7a3c37b3d34f4a676a1e484efe
patches: []
resources:
  - ../main
