apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: arikkfir-merge-branch-and-pr-workflows
images:
  - name: ghcr.io/arikkfir/greenstar/backend
    newTag: 94fcdbb1bff7179260fea29b7c58b19a7cfabfb9
  - name: ghcr.io/arikkfir/greenstar/frontend
    newTag: 94fcdbb1bff7179260fea29b7c58b19a7cfabfb9
  - name: ghcr.io/arikkfir/greenstar/migrations
    newTag: 94fcdbb1bff7179260fea29b7c58b19a7cfabfb9
  - name: ghcr.io/arikkfir/greenstar/neo4j
    newTag: 94fcdbb1bff7179260fea29b7c58b19a7cfabfb9
patches: []
resources:
  - ../main
