nameReference:
  - kind: Secret
    version: v1
    fieldSpecs:
      - group: traefik.io
        version: v1alpha1
        kind: IngressRoute
        path: spec/tls/secretName
      - group: traefik.io
        version: v1alpha1
        kind: IngressRouteTCP
        path: spec/tls/secretName
  - kind: Service
    version: v1
    fieldSpecs:
      - group: traefik.io
        version: v1alpha1
        kind: IngressRoute
        path: spec/routes/services/name
      - group: traefik.io
        version: v1alpha1
        kind: IngressRouteTCP
        path: spec/routes/services/name
  - kind: ServiceAccount
    version: v1
    fieldSpecs:
      - group: external-secrets.io
        version: v1beta1
        kind: SecretStore
        path: spec/provider/gcpsm/auth/workloadIdentity/serviceAccountRef/name
  - group: iam.cnrm.cloud.google.com
    version: v1beta1
    kind: IAMServiceAccount
    fieldSpecs:
      - group: iam.cnrm.cloud.google.com
        version: v1beta1
        kind: IAMPolicyMember
        path: spec/memberFrom/serviceAccountRef/name
      - group: iam.cnrm.cloud.google.com
        version: v1beta1
        kind: IAMPolicyMember
        path: spec/resourceRef/name
  - group: external-secrets.io
    version: v1beta1
    kind: SecretStore
    fieldSpecs:
      - group: external-secrets.io
        version: v1beta1
        kind: ExternalSecret
        path: spec/secretStoreRef/name
  - group: external-secrets.io
    version: v1beta1
    kind: ClusterSecretStore
    fieldSpecs:
      - group: external-secrets.io
        version: v1beta1
        kind: ExternalSecret
        path: spec/secretStoreRef/name
