apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: 75-move-deployment-m-repository
images:
  - name: ghcr.io/arikkfir/greenstar/backend
    newTag: f04174a3c072dde5eed16cc6ca0ed6c9a1466892
  - name: ghcr.io/arikkfir/greenstar/frontend
    newTag: f04174a3c072dde5eed16cc6ca0ed6c9a1466892
  - name: ghcr.io/arikkfir/greenstar/migrations
    newTag: f04174a3c072dde5eed16cc6ca0ed6c9a1466892
  - name: ghcr.io/arikkfir/greenstar/neo4j
    newTag: f04174a3c072dde5eed16cc6ca0ed6c9a1466892
patches: []
resources:
  - ../../apps/echo-server
  - https://github.com/arikkfir/greenstar.git//deploy?ref=f04174a3c072dde5eed16cc6ca0ed6c9a1466892
