apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: 75-move-deployment-m-repository
images:
  - name: ghcr.io/arikkfir/greenstar/backend
    newTag: f04174a3c072dde5eed16cc6ca0ed6c9a1466892
  - name: ghcr.io/arikkfir/greenstar/frontend
    newTag: f04174a3c072dde5eed16cc6ca0ed6c9a1466892
  - name: ghcr.io/arikkfir/greenstar/migrations
    newTag: f04174a3c072dde5eed16cc6ca0ed6c9a1466892
  - name: ghcr.io/arikkfir/greenstar/neo4j
    newTag: f04174a3c072dde5eed16cc6ca0ed6c9a1466892
patches:
  - patch: |
      - op: replace
        path: /spec/replicas
        value: 0
    target:
      group: apps
      version: v1
      kind: Deployment
  - patch: |
      - op: replace
        path: /spec/values/replicaCount
        value: 0
    target:
      group: helm.toolkit.fluxcd.io
      version: v2beta1
      kind: HelmRelease
  - patch: |
      - op: replace
        path: /spec/replicas
        value: 0
    target:
      group: apps
      version: v1
      kind: StatefulSet
resources:
  - ../../apps/echo-server
  - https://github.com/arikkfir/greenstar.git//deploy?ref=f04174a3c072dde5eed16cc6ca0ed6c9a1466892
