apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: 75-move-deployment-m-repository
commonAnnotations:
  kfirs.com/branch: 75-move-deployment-manifests-back-to-this-repository
  kfirs.com/environment: 75-move-deployment-m-repository
resources:
  - ../main
patches:
  - patch: |-
      - op: replace
        path: /metadata/name
        value: 75-move-deployment-m-repository
    target:
      group: ""
      version: v1
      kind: Namespace

  # Fix the branch & environment substitutions of all kustomizations
  - patch: |
      - op: replace
        path: /spec/targetNamespace
        value: 75-move-deployment-m-repository
      - op: replace
        path: /spec/postBuild/substitute/deploy_environment
        value: 75-move-deployment-m-repository
      - op: add
        path: /spec/patches/-
        value:
          target:
            group: cert-manager.io
            version: v1
            kind: Certificate
          patch: |-
            - op: replace
              path: /spec/issuerRef/name
              value: google-clouddns
    target:
      group: kustomize.toolkit.fluxcd.io
      version: v1
      kind: Kustomization
