apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels: {}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels: {}
    spec:
      containers:
        - image: ghcr.io/arikkfir/greenstar/frontend
          name: frontend
          livenessProbe:
            httpGet:
              port: http
              path: /
            failureThreshold: 3
            periodSeconds: 30
            terminationGracePeriodSeconds: 30
            timeoutSeconds: 5
          ports:
            - containerPort: 80
              name: http
          readinessProbe:
            httpGet:
              port: http
              path: /
            failureThreshold: 3
            periodSeconds: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 200m
              memory: 64Gi
            requests:
              cpu: 200m
              memory: 32Mi
          startupProbe:
            httpGet:
              port: http
              path: /
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 1
            timeoutSeconds: 1
      enableServiceLinks: false
      serviceAccountName: frontend
