apiVersion: dns.cnrm.cloud.google.com/v1beta1
kind: DNSRecordSet
metadata:
  name: echo-kfirs-com-a
spec:
  name: echo.kfirs.com.
  type: CNAME
  ttl: 300
  managedZoneRef:
    name: kfirs-com
    namespace: domains
  rrdatas:
    - traefik.kfirs.com.
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: echo-kfirs-com
spec:
  secretName: echo-kfirs-com-tls
  issuerRef:
    kind: ClusterIssuer
    name: google-clouddns
  dnsNames:
    - echo.kfirs.com
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: echoserver-https
spec:
  entryPoints: [websecure]
  routes:
    - kind: Rule
      match: Host(`echo.kfirs.com`)
      services:
        - kind: Service
          name: echoserver-echo-server
          namespace: echoserver
          port: http
  tls:
    secretName: echo-kfirs-com-tls
