apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: echo-server
spec:
  interval: 5m
  chart:
    spec:
      chart: echo-server
      sourceRef:
        kind: HelmRepository
        name: echo-server
        namespace: default
  values:
    application:
      enable:
        cookies: true
        environment: false
        file: true
        header: true
        host: true
        http: true
        request: true
    image:
      tag: 0.7.1
    ingress:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.priority: "200" # TODO: do we need this?
      hosts:
        - host: "${deploy_environment}.echo.kfirs.com"
          paths:
            - /
      tls:
        - hosts:
            - "${deploy_environment}.echo.kfirs.com"
          secretName: echoserver-tls
    nodeSelector:
      node.kfirs.com/role: work
    replicaCount: 1
    resources:
      limits:
        cpu: 50m
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 128Mi
    tolerations:
      - effect: NoExecute
        key: node.kfirs.com/role
        operator: Equal
        value: work
