apiVersion: dns.cnrm.cloud.google.com/v1beta1
kind: DNSRecordSet
metadata:
  name: a-record
spec:
  name: "${flux_environment}.echo.kfirs.com."
  type: CNAME
  ttl: 300
  managedZoneRef:
    name: kfirs-com
    namespace: dns
  # noinspection KubernetesDeprecatedKeys
  rrdatas:
    - traefik.kfirs.com.
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: root
spec:
  secretName: echoserver-tls
  issuerRef:
    kind: ClusterIssuer
    name: google-clouddns
  commonName: "${flux_environment:0:48}.echo.kfirs.com"
  dnsNames:
    - "${flux_environment:0:48}.echo.kfirs.com"
    - "${flux_environment}.echo.kfirs.com"
