apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Alert
metadata:
  name: environments
  namespace: flux-system
spec:
  providerRef:
    name: github
  eventSeverity: info
  eventSources:
    - kind: Kustomization
      name: '*'
      namespace: default
    - kind: Kustomization
      name: '*'
      namespace: flux-system
