apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: greenstar-api@arikkfir.iam.gserviceaccount.com
  labels:
    app.kubernetes.io/component: backend
  name: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: backend
  name: backend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: backend
  template:
    metadata:
      labels:
        app.kubernetes.io/component: backend
    spec:
      containers:
        - image: ghcr.io/arikkfir/greenstar/backend
          args:
            - --http.access-log-excluded-headers=sec\-.*
            - --http.access-log-excluded-headers=vary
            - --http.access-log-excluded-headers=x-request-id
          name: backend
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NEO4J_HOST
              value: greenstar-neo4j.$(POD_NAMESPACE)
            - name: NEO4J_PORT
              value: "7687"
            - name: REDIS_HOST
              value: greenstar-redis.$(POD_NAMESPACE)
            - name: REDIS_PORT
              value: "6379"
            - name: HTTP_CORS_ALLOWED_ORIGINS
              value: "https://*.${flux_environment}.greenstar.kfirs.com"
          envFrom:
            - secretRef:
                name: descope
                optional: false
          livenessProbe:
            httpGet:
              port: health
              path: /healthz
            failureThreshold: 3
            periodSeconds: 5
            terminationGracePeriodSeconds: 30
            timeoutSeconds: 3
          ports:
            - containerPort: 8000
              name: http
            - containerPort: 9000
              name: health
          readinessProbe:
            httpGet:
              port: health
              path: /healthz
            failureThreshold: 3
            periodSeconds: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 100m
              memory: 64Mi
            requests:
              cpu: 100m
              memory: 64Mi
          startupProbe:
            httpGet:
              port: health
              path: /healthz
            failureThreshold: 5
            periodSeconds: 1
            timeoutSeconds: 1
      enableServiceLinks: false
      serviceAccountName: backend
