apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: traefik-google-oidc-auth
spec:
  displayName: traefik-google-oidc-auth
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: traefik-google-oidc-auth-gcp-secret-viewer
spec:
  memberFrom:
    serviceAccountRef:
      name: traefik-google-oidc-auth
  role: roles/secretmanager.viewer
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: projects/8909046976
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: traefik-google-oidc-auth-gcp-secret-accessor
spec:
  memberFrom:
    serviceAccountRef:
      name: traefik-google-oidc-auth
  role: roles/secretmanager.secretAccessor
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: projects/8909046976
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: traefik-google-oidc-auth-secret-store
spec:
  provider:
    gcpsm:
      projectID: arikkfir
      auth:
        workloadIdentity:
          clusterLocation: me-west1
          clusterName: primary
          serviceAccountRef:
            name: traefik-google-oidc-auth
            namespace: traefik
