apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: traefik-google-oidc-auth-secret-provider
spec:
  provider: gcp
  secretObjects:
    - data:
        - key: client_id
          objectName: google-arikkfir-kfirs-oauth-app-client-id
        - key: client_secret
          objectName: google-arikkfir-kfirs-oauth-app-client-secret
        - key: signing_secret
          objectName: google-arikkfir-kfirs-oauth-app-signing-secret
      secretName: traefik-google-oidc-auth
      type: Opaque
