apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: traefik-google-oidc-auth
spec:
  refreshInterval: 30m
  secretStoreRef:
    kind: SecretStore
    name: traefik-google-oidc-auth-secret-store
  target:
    name: traefik-google-oidc-auth
    creationPolicy: Owner
  data:
    - secretKey: client_id
      remoteRef:
        key: google-arikkfir-kfirs-oauth-app-client-id
    - secretKey: client_secret
      remoteRef:
        key: google-arikkfir-kfirs-oauth-app-client-secret
    - secretKey: signing_secret
      remoteRef:
        key: google-arikkfir-kfirs-oauth-app-signing-secret
