apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: arikkfir-65-improve-workflows-performance
images:
  - name: ghcr.io/arikkfir/greenstar/backend
    newTag: e16af8c9073dc492ec7d9ba315215136e01cf08b
  - name: ghcr.io/arikkfir/greenstar/frontend
    newTag: e16af8c9073dc492ec7d9ba315215136e01cf08b
  - name: ghcr.io/arikkfir/greenstar/migrations
    newTag: e16af8c9073dc492ec7d9ba315215136e01cf08b
  - name: ghcr.io/arikkfir/greenstar/neo4j
    newTag: e16af8c9073dc492ec7d9ba315215136e01cf08b
patches: []
resources:
  - ../main
