apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: arikkfir-65-improve-workflows-performance
images:
  - name: ghcr.io/arikkfir/greenstar/backend
    newTag: e60cb5034eaf7ef36a6512fe21e58bc990e6424a
  - name: ghcr.io/arikkfir/greenstar/frontend
    newTag: e60cb5034eaf7ef36a6512fe21e58bc990e6424a
  - name: ghcr.io/arikkfir/greenstar/migrations
    newTag: e60cb5034eaf7ef36a6512fe21e58bc990e6424a
  - name: ghcr.io/arikkfir/greenstar/neo4j
    newTag: e60cb5034eaf7ef36a6512fe21e58bc990e6424a
patches: []
resources:
  - ../main
