apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: arikkfir-65-improve-workflows-performance
images:
  - name: ghcr.io/arikkfir/greenstar/backend
    newTag: 203d1dd5131b845f7bceb970ebce223498c677bd
  - name: ghcr.io/arikkfir/greenstar/frontend
    newTag: 203d1dd5131b845f7bceb970ebce223498c677bd
  - name: ghcr.io/arikkfir/greenstar/migrations
    newTag: 203d1dd5131b845f7bceb970ebce223498c677bd
  - name: ghcr.io/arikkfir/greenstar/neo4j
    newTag: 203d1dd5131b845f7bceb970ebce223498c677bd
patches: []
resources:
  - ../main
