apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: arikkfir-65-improve-workflows-performance
images:
  - name: ghcr.io/arikkfir/greenstar/backend
    newTag: f8c94cabcb98df18287b619050fbdfcd4c30a380
  - name: ghcr.io/arikkfir/greenstar/frontend
    newTag: f8c94cabcb98df18287b619050fbdfcd4c30a380
  - name: ghcr.io/arikkfir/greenstar/migrations
    newTag: f8c94cabcb98df18287b619050fbdfcd4c30a380
  - name: ghcr.io/arikkfir/greenstar/neo4j
    newTag: f8c94cabcb98df18287b619050fbdfcd4c30a380
patches: []
resources:
  - ../main
