apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: arikkfir-65-improve-workflows-performance
images:
  - name: ghcr.io/arikkfir/greenstar/backend
    newTag: 40f55283433c90cf767a79f81731ea353716de55
  - name: ghcr.io/arikkfir/greenstar/frontend
    newTag: 40f55283433c90cf767a79f81731ea353716de55
  - name: ghcr.io/arikkfir/greenstar/migrations
    newTag: 40f55283433c90cf767a79f81731ea353716de55
  - name: ghcr.io/arikkfir/greenstar/neo4j
    newTag: 40f55283433c90cf767a79f81731ea353716de55
patches: []
resources:
  - ../main
