apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: arikkfir-65-improve-workflows-performance
images:
  - name: ghcr.io/arikkfir/greenstar/backend
    newTag: 41ae50ace87842af670efcabda9118552f4f21f0
  - name: ghcr.io/arikkfir/greenstar/frontend
    newTag: 41ae50ace87842af670efcabda9118552f4f21f0
  - name: ghcr.io/arikkfir/greenstar/migrations
    newTag: 41ae50ace87842af670efcabda9118552f4f21f0
  - name: ghcr.io/arikkfir/greenstar/neo4j
    newTag: 41ae50ace87842af670efcabda9118552f4f21f0
patches: []
resources:
  - ../main
