apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: traefik-google-oidc-auth
spec:
  interval: 5m
  url: https://arikkfir.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik-google-oidc-auth
spec:
  interval: 5m
  chart:
    spec:
      chart: traefik-google-oidc-auth
      version: v0.2.0
      sourceRef:
        kind: HelmRepository
        name: traefik-google-oidc-auth
  values:
    oauth:
      clientId:
        secretName: traefik-google-oidc-auth
        key: client_id
      clientSecret:
        secretName: traefik-google-oidc-auth
        key: client_secret
      host: oauth2.kfirs.com
    security:
      userCookie:
        name: X-Kfirs-Auth
        domain: .kfirs.com
      hashingSecret:
        secretName: traefik-google-oidc-auth
        key: signing_secret
      allowedDomains:
        - kfirs.com
        - kfirfamily.com
    deployment:
      nodeSelector:
        gke.kfirs.com/purpose: workloads
      tolerations:
        - effect: NoExecute
          key: gke.kfirs.com/purpose
          operator: Equal
          value: workloads
    serviceAccount:
      annotations:
        iam.gke.io/gcp-service-account: traefik-google-auth@arikkfir.iam.gserviceaccount.com
