apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: traefik-google-auth-secret-store
spec:
  provider:
    gcpsm:
      projectID: arikkfir
      auth:
        workloadIdentity:
          clusterLocation: me-west1-a
          clusterName: primary
          serviceAccountRef:
            name: traefik-google-oidc-auth-server
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: traefik-google-oidc-auth
spec:
  refreshInterval: 30m
  secretStoreRef:
    kind: SecretStore
    name: traefik-google-auth-secret-store
  target:
    name: traefik-google-oidc-auth
    creationPolicy: Owner
  data:
    - secretKey: client_id
      remoteRef:
        key: google-arikkfir-kfirs-oauth-app-client-id
    - secretKey: client_secret
      remoteRef:
        key: google-arikkfir-kfirs-oauth-app-client-secret
    - secretKey: signing_secret
      remoteRef:
        key: google-arikkfir-kfirs-oauth-app-signing-secret
