apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  ports:
    - name: client-nontls
      port: 6379
      protocol: TCP
      targetPort: client-nontls
  type: ClusterIP
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: redis-tls
spec:
  entryPoints: [ redis ]
  routes:
    - match: HostSNI(`redis.${flux_environment}.greenstar.kfirs.com`)
      middlewares:
        - name: ip-whitelist-tcp
          namespace: traefik
      priority: 100 # TODO: do we need priority here? does it conflict with non-TCP ingress?
      services:
        - name: redis
          port: client-nontls
  tls:
    secretName: greenstar-wildcard-tls
