apiVersion: apps/v1
kind: Deployment
metadata:
  name: playwright
spec:
  selector:
    matchLabels: {}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
        gke-gcsfuse/volumes: "true"
        gke-gcsfuse/cpu-limit: 100m
      labels: {}
    spec:
      containers:
        - image: nginx:1.23
          name: nginx
          ports:
            - containerPort: 80
              name: http
          resources:
            limits:
              cpu: 50m
              memory: 64Gi
            requests:
              cpu: 50m
              memory: 32Mi
          volumeMounts:
            - name: gcs-fuse-arikkfir-playwright-reports
              mountPath: /usr/share/nginx/html
              readOnly: true
      enableServiceLinks: false
      nodeSelector:
        node.kfirs.com/role: work
      serviceAccountName: playwright-server
      tolerations:
        - effect: NoExecute
          key: node.kfirs.com/role
          operator: Equal
          value: work
      volumes:
        - name: gcs-fuse-arikkfir-playwright-reports
          csi:
            driver: gcsfuse.csi.storage.gke.io
            readOnly: true
            volumeAttributes:
              bucketName: arikkfir-playwright-reports
              mountOptions: "implicit-dirs"
