apiVersion: dns.cnrm.cloud.google.com/v1beta1
kind: DNSRecordSet
metadata:
  name: playwright-a-record
spec:
  name: "playwright.kfirs.com."
  type: CNAME
  ttl: 300
  managedZoneRef:
    name: kfirs-com
    namespace: dns
  # noinspection KubernetesDeprecatedKeys
  rrdatas:
    - traefik.kfirs.com.
