apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: playwright-server
spec:
  displayName: Playwright server Service Account
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: playwright-server-ksa-link
spec:
  member: serviceAccount:arikkfir.svc.id.goog[playwright/playwright-server]
  role: roles/iam.workloadIdentityUser
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    name: playwright-server
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: playwright-server-storage-object-viewer
spec:
  memberFrom:
    serviceAccountRef:
      name: playwright-server
  role: roles/storage.objectViewer
  resourceRef:
    apiVersion: storage.cnrm.cloud.google.com/v1beta1
    kind: StorageBucket
    external: arikkfir-playwright-reports
