apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: playwright-uploader
spec:
  displayName: Playwright Uploader Service Account
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: playwright-uploader-oidc-link
spec:
  member: principalSet://iam.googleapis.com/projects/8909046976/locations/global/workloadIdentityPools/github-actions/attribute.repository_owner/arikkfir
  role: roles/iam.workloadIdentityUser
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    name: playwright-uploader
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: playwright-uploader-storage-object-creator
spec:
  memberFrom:
    serviceAccountRef:
      name: playwright-uploader
  role: roles/storage.objectCreator
  resourceRef:
    apiVersion: storage.cnrm.cloud.google.com/v1beta1
    kind: StorageBucket
    external: arikkfir-playwright-reports
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: playwright-uploader-storage-object-viewer
spec:
  memberFrom:
    serviceAccountRef:
      name: playwright-uploader
  role: roles/storage.objectViewer
  resourceRef:
    apiVersion: storage.cnrm.cloud.google.com/v1beta1
    kind: StorageBucket
    external: arikkfir-playwright-reports
