apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: flux-github-token
  namespace: default
spec:
  refreshInterval: 10m
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-manager # TODO: create a special GCP ClusterSecretStore just for the limited GitHub token
  data:
    - secretKey: token
      remoteRef:
        key: flux-greenstar-github-token # TODO: rename GCP secret to just "flux-github-token"
