apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dependabot-docker-migrations-neo4j-5-11-enterprise
images:
  - name: ghcr.io/arikkfir/greenstar/backend
    newTag: 3ee08cfb1705fb083a48615c9fee421329f972ae
  - name: ghcr.io/arikkfir/greenstar/frontend
    newTag: 3ee08cfb1705fb083a48615c9fee421329f972ae
  - name: ghcr.io/arikkfir/greenstar/migrations
    newTag: 3ee08cfb1705fb083a48615c9fee421329f972ae
  - name: ghcr.io/arikkfir/greenstar/neo4j
    newTag: 3ee08cfb1705fb083a48615c9fee421329f972ae
patches: []
resources:
  - ../main
