apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

resources:
- gcp-iam.yaml
- https://github.com/GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp/raw/main/deploy/provider-gcp-plugin.yaml

patches:
  - target:
      kind: ServiceAccount
      name: secrets-store-csi-driver-provider-gcp
    patch: |
      - op: add
        path: /metadata/annotations/iam.gke.io~1gcp-service-account
        value: secrets-store-csi-driver-gcp@arikkfir.iam.gserviceaccount.com
  - target:
      kind: DaemonSet
      labelSelector: app=csi-secrets-store-provider-gcp
    patch: |
      - op: add
        path: /spec/template/spec/nodeSelector/gke.kfirs.com~1purpose
        value: workloads
      - op: add
        path: /spec/template/spec/tolerations
        value:
          - key: gke.kfirs.com/purpose
            operator: Equal
            value: workloads
            effect: NoExecute
