apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fix-pr-deploy-comment-workflow
resources:
  - ../_commons/namespace.yaml
  - ../_commons/echo-server.yaml
  - ../_commons/greenstar
