apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: greenstar
spec:
  commonMetadata:
    annotations:
      kfirs.com/branch: "${BRANCH}"
      kfirs.com/environment: "${ENVIRONMENT}"
  force: true
  healthChecks: []
  images: []
  interval: 5m
  patches: []
  path: /
  postBuild:
    substitute:
      deploy_branch: "${BRANCH}"
      deploy_environment: "${ENVIRONMENT}"
  prune: true
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: greenstar
    namespace: "${ENVIRONMENT}"
  targetNamespace: "${ENVIRONMENT}"
  timeout: 5m
