apiVersion: dns.cnrm.cloud.google.com/v1beta1
kind: DNSManagedZone
metadata:
  annotations:
    cnrm.cloud.google.com/deletion-policy: abandon
  name: yellow-mint-com
  namespace: dns
spec:
  description: yellow-mint.com DNS zone
  dnsName: yellow-mint.com.
---
apiVersion: dns.cnrm.cloud.google.com/v1beta1
kind: DNSRecordSet
metadata:
  annotations:
    cnrm.cloud.google.com/deletion-policy: abandon
  name: yellow-mint-com-mx
  namespace: dns
spec:
  name: yellow-mint.com.
  type: MX
  ttl: 300
  managedZoneRef:
    name: yellow-mint-com
  # noinspection KubernetesDeprecatedKeys
  rrdatas:
    - "10 aspmx.l.google.com."
    - "20 alt1.aspmx.l.google.com."
    - "30 alt2.aspmx.l.google.com."
    - "40 aspmx2.googlemail.com."
    - "50 aspmx3.googlemail.com."
---
apiVersion: dns.cnrm.cloud.google.com/v1beta1
kind: DNSRecordSet
metadata:
  annotations:
    cnrm.cloud.google.com/deletion-policy: abandon
  name: yellow-mint-com-txt
  namespace: dns
spec:
  name: yellow-mint.com.
  type: TXT
  ttl: 300
  managedZoneRef:
    name: yellow-mint-com
  # noinspection KubernetesDeprecatedKeys
  rrdatas:
    - "\"google-site-verification=O1bnEargTjdOdUMcpWvuMeDg4wuFFr-szWsCfijOPiU\""
---
apiVersion: dns.cnrm.cloud.google.com/v1beta1
kind: DNSRecordSet
metadata:
  annotations:
    cnrm.cloud.google.com/deletion-policy: abandon
  name: yellow-mint-com-apex
  namespace: dns
spec:
  name: yellow-mint.com.
  type: A
  ttl: 300
  managedZoneRef:
    name: yellow-mint-com
  # noinspection KubernetesDeprecatedKeys
  rrdatas:
    - 23.236.62.147
---
apiVersion: dns.cnrm.cloud.google.com/v1beta1
kind: DNSRecordSet
metadata:
  annotations:
    cnrm.cloud.google.com/deletion-policy: abandon
  name: www-yellow-mint-com-cname
  namespace: dns
spec:
  name: www.yellow-mint.com.
  type: CNAME
  ttl: 300
  managedZoneRef:
    name: yellow-mint-com
  # noinspection KubernetesDeprecatedKeys
  rrdatas:
    - www80.wixdns.net.
