apiVersion: dns.cnrm.cloud.google.com/v1beta1
kind: DNSManagedZone
metadata:
  annotations:
    cnrm.cloud.google.com/deletion-policy: abandon
  name: kfirs-com
  namespace: dns
spec:
  description: kfirs.com DNS zone
  dnsName: kfirs.com.
---
apiVersion: dns.cnrm.cloud.google.com/v1beta1
kind: DNSRecordSet
metadata:
  annotations:
    cnrm.cloud.google.com/deletion-policy: abandon
  name: kfirs-com-mx
  namespace: dns
spec:
  name: kfirs.com.
  type: MX
  ttl: 300
  managedZoneRef:
    name: kfirs-com
  # noinspection KubernetesDeprecatedKeys
  rrdatas:
    - "10 aspmx.l.google.com."
    - "20 alt1.aspmx.l.google.com."
    - "30 alt2.aspmx.l.google.com."
    - "40 aspmx2.googlemail.com."
    - "50 aspmx3.googlemail.com."
---
apiVersion: dns.cnrm.cloud.google.com/v1beta1
kind: DNSRecordSet
metadata:
  annotations:
    cnrm.cloud.google.com/deletion-policy: abandon
  name: kfirs-com-txt
  namespace: dns
spec:
  name: kfirs.com.
  type: TXT
  ttl: 300
  managedZoneRef:
    name: kfirs-com
  # noinspection KubernetesDeprecatedKeys
  rrdatas:
    - "\"google-site-verification=y-YsxIliC1sD5JyFKoa3hW6iEenSgpWvvaN-VAgBaJE\""
    - "\"google-site-verification=JWU6IFxHRHNe6tJpD16tv1ufQBR2_LPMxlTsZDdOzq4\""
---
apiVersion: dns.cnrm.cloud.google.com/v1beta1
kind: DNSRecordSet
metadata:
  annotations:
    cnrm.cloud.google.com/deletion-policy: abandon
  name: kfirs-com-apex
  namespace: dns
spec:
  name: kfirs.com.
  type: A
  ttl: 300
  managedZoneRef:
    name: kfirs-com
  # noinspection KubernetesDeprecatedKeys
  rrdatas:
    - 185.199.108.153
    - 185.199.109.153
    - 185.199.110.153
    - 185.199.111.153
---
apiVersion: dns.cnrm.cloud.google.com/v1beta1
kind: DNSRecordSet
metadata:
  annotations:
    cnrm.cloud.google.com/deletion-policy: abandon
  name: www-kfirs-com-cname
  namespace: dns
spec:
  name: www.kfirs.com.
  type: CNAME
  ttl: 300
  managedZoneRef:
    name: kfirs-com
  # noinspection KubernetesDeprecatedKeys
  rrdatas:
    - arikkfir.github.io.
---
apiVersion: dns.cnrm.cloud.google.com/v1beta1
kind: DNSRecordSet
metadata:
  annotations:
    cnrm.cloud.google.com/deletion-policy: abandon
  name: art-cbt-kfirs-com-cname
  namespace: dns
spec:
  name: art-cbt.kfirs.com.
  type: CNAME
  ttl: 300
  managedZoneRef:
    name: kfirs-com
  # noinspection KubernetesDeprecatedKeys
  rrdatas:
    - www80.wixdns.net.
---
apiVersion: dns.cnrm.cloud.google.com/v1beta1
kind: DNSRecordSet
metadata:
  annotations:
    cnrm.cloud.google.com/deletion-policy: abandon
  name: www-art-cbt-kfirs-com-cname
  namespace: dns
spec:
  name: www.art-cbt.kfirs.com.
  type: CNAME
  ttl: 300
  managedZoneRef:
    name: kfirs-com
  # noinspection KubernetesDeprecatedKeys
  rrdatas:
    - www80.wixdns.net.
