apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dependabot-npm-and-y-dom-6-16-0
images:
  - name: ghcr.io/arikkfir/greenstar/backend
    newTag: 9321bddcd92d82044e8f4ea27fcaa8acbadd216a
  - name: ghcr.io/arikkfir/greenstar/frontend
    newTag: 9321bddcd92d82044e8f4ea27fcaa8acbadd216a
  - name: ghcr.io/arikkfir/greenstar/migrations
    newTag: 9321bddcd92d82044e8f4ea27fcaa8acbadd216a
  - name: ghcr.io/arikkfir/greenstar/neo4j
    newTag: 9321bddcd92d82044e8f4ea27fcaa8acbadd216a
patches: []
resources:
  - ../main
