apiVersion: v1
kind: Namespace
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: arikkfir
  name: domains
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: domains
  namespace: domains
spec:
  dependsOn:
    - name: gke
      namespace: cnrm-system
  interval: 5m
  path: platform/domains
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
