apiVersion: v1
kind: Namespace
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: arikkfir
  name: traefik
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: traefik
  namespace: traefik
spec:
  dependsOn:
    - name: gke
      namespace: cnrm-system
    - name: cert-manager
      namespace: cert-manager
    - name: domains
      namespace: domains
    - name: external-secrets
      namespace: external-secrets
  interval: 10m
  path: platform/traefik/traefik
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
  timeout: 8m # LoadBalancer service might take a little while to sync in GCP
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: traefik-google-auth
  namespace: traefik
spec:
  dependsOn:
    - name: traefik
      namespace: traefik
  interval: 5m
  path: platform/traefik/traefik-google-auth
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: traefik-dashboard
  namespace: traefik
spec:
  dependsOn:
    - name: traefik-google-auth
      namespace: traefik
  interval: 5m
  path: platform/traefik/traefik-dashboard
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
