apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dependabot-npm-and-y-ct-18-2-21
images:
  - name: ghcr.io/arikkfir/greenstar/backend
    newTag: cea3dfe1681c387e1573a2e32a4d9862aec37d8b
  - name: ghcr.io/arikkfir/greenstar/frontend
    newTag: cea3dfe1681c387e1573a2e32a4d9862aec37d8b
  - name: ghcr.io/arikkfir/greenstar/migrations
    newTag: cea3dfe1681c387e1573a2e32a4d9862aec37d8b
  - name: ghcr.io/arikkfir/greenstar/neo4j
    newTag: cea3dfe1681c387e1573a2e32a4d9862aec37d8b
patches:
  - patch: |
      - op: replace
        path: /spec/replicas
        value: 0
    target:
      group: apps
      version: v1
      kind: Deployment
  - patch: |
      - op: replace
        path: /spec/values/replicaCount
        value: 0
    target:
      group: helm.toolkit.fluxcd.io
      version: v2beta1
      kind: HelmRelease
  - patch: |
      - op: replace
        path: /spec/replicas
        value: 0
    target:
      group: apps
      version: v1
      kind: StatefulSet
resources:
  - ../main
