apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik-kfirs-com
  namespace: traefik
spec:
  secretName: traefik-kfirs-com-tls
  issuerRef:
    kind: ClusterIssuer
    name: google-clouddns
  dnsNames:
    - traefik.kfirs.com
