apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: traefik-google-oidc-auth
spec:
  interval: 1m
  url: https://arikkfir.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik-google-oidc-auth
spec:
  interval: 1m
  chart:
    spec:
      chart: traefik-google-oidc-auth
      version: 0.1.0-pr1-18
      sourceRef:
        kind: HelmRepository
        name: traefik-google-oidc-auth
      interval: 1m
  values:
    oauth:
      clientId:
        secretName: kfirs-oauth-app
        key: client_id
      clientSecret:
        secretName: kfirs-oauth-app
        key: client_secret
      host: oauth.kfirs.com
    cookieName: X-Kfirs-Auth
    security:
      csrfCookieName: X-Kfirs-Protect
      signingSecret:
        secretName: kfirs-oauth-app
        key: signing_secret
      allowedUserDomains:
        - kfirs.com
        - kfirfamily.com
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: google-auth
spec:
  forwardAuth:
    address: http://traefik-google-oidc-auth-server:80/verify
    trustForwardHeader: true
    authResponseHeaders:
      - Set-Cookie
---
apiVersion: dns.cnrm.cloud.google.com/v1beta1
kind: DNSRecordSet
metadata:
  name: oauth-kfirs-com-a
spec:
  name: oauth.kfirs.com.
  type: CNAME
  ttl: 300
  managedZoneRef:
    name: kfirs-com
    namespace: domains
  rrdatas:
    - traefik.kfirs.com.
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: oauth-kfirs-com
spec:
  secretName: oauth-kfirs-com-tls
  issuerRef:
    kind: ClusterIssuer
    name: google-clouddns
  dnsNames:
    - oauth.kfirs.com
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: oauth-http
spec:
  entryPoints: [web]
  routes:
    - kind: Rule
      match: Host(`oauth.kfirs.com`)
      middlewares:
        - name: redirect-to-https
      services:
        - kind: Service
          name: traefik-google-oidc-auth-server
          port: http
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: oauth-https
spec:
  entryPoints: [websecure]
  routes:
    - kind: Rule
      match: Host(`oauth.kfirs.com`)
      services:
        - kind: Service
          name: traefik-google-oidc-auth-server
          port: http
  tls:
    secretName: oauth-kfirs-com-tls
