apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 5m
  chart:
    spec:
      chart: traefik
      version: 24.0.0
      sourceRef:
        kind: HelmRepository
        name: traefik
  values:
    ingressClass:
      enabled: true
      isDefaultClass: true
    ingressRoute:
      dashboard:
        enabled: true
        matchRule: Host(`traefik.kfirs.com`)
        entryPoints: [websecure]
        middlewares: [ip-whitelist]
        tls:
          secretName: traefik-kfirs-com-tls
    providers:
      kubernetesCRD:
        enabled: true
        allowCrossNamespace: true
        allowExternalNameServices: true
        allowEmptyServices: true
      kubernetesIngress:
        enabled: true
        allowExternalNameServices: true
        allowEmptyServices: true
    logs:
      general:
        format: json
        level: INFO
      access:
        enabled: true
        format: json
        fields:
          general:
            defaultmode: keep
          headers:
            defaultmode: keep
            names:
              Authorization: redact
    metrics:
      prometheus:
        entryPoint: metrics
    ports:
      web:
        redirectTo: websecure
      redis:
        port: 6379
        containerPort: 6379
        expose: true
        exposedPort: 6379
        targetPort: 6379
        advertisedPort: 6379
        tls:
          enabled: true
      bolt:
        port: 7687
        containerPort: 7687
        expose: true
        exposedPort: 7687
        targetPort: 7687
        advertisedPort: 7687
        tls:
          enabled: true
    service:
      spec:
        externalTrafficPolicy: Local
        loadBalancerIP: 1.2.3.4
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 3
      metrics:
        - type: Resource
          resource:
            name: cpu
            target:
              type: Utilization
              averageUtilization: 60
        - type: Resource
          resource:
            name: memory
            target:
              type: Utilization
              averageUtilization: 60
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 300
          policies:
            - type: Pods
              value: 1
              periodSeconds: 60
    resources:
      requests:
        cpu: 200m
        memory: 100Mi
      limits:
        cpu: 500m
        memory: 200Mi
    nodeSelector:
      node.kfirs.com/role: work
    tolerations:
      - effect: NoExecute
        key: node.kfirs.com/role
        operator: Equal
        value: work
    extraObjects:
      - apiVersion: traefik.io/v1alpha1
        kind: Middleware
        metadata:
          name: ip-whitelist
          namespace: traefik
        spec:
          ipWhiteList:
            sourceRange:
              - 192.30.252.0/22
              - 185.199.108.0/22
              - 140.82.112.0/20
              - 143.55.64.0/20
              - 85.64.215.183/32
              - 62.90.112.29/32
      - apiVersion: traefik.io/v1alpha1
        kind: MiddlewareTCP
        metadata:
          name: ip-whitelist-tcp
          namespace: traefik
        spec:
          ipWhiteList:
            sourceRange:
              - 192.30.252.0/22
              - 185.199.108.0/22
              - 140.82.112.0/20
              - 143.55.64.0/20
              - 85.64.215.183/32
              - 62.90.112.29/32

  # This prevents "reconciliation failed: install retries exhausted" errors
#  install:
#    disableWait: true
#  upgrade:
#    disableWait: true
