apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeAddress
metadata:
  name: traefik-ingress
spec:
  addressType: EXTERNAL
  description: GKE Ingress
  ipVersion: IPV4
  location: europe-west3
---
apiVersion: dns.cnrm.cloud.google.com/v1beta1
kind: DNSRecordSet
metadata:
  name: traefik-kfirs-com-a
spec:
  name: traefik.kfirs.com.
  type: A
  ttl: 300
  managedZoneRef:
    name: kfirs-com
    namespace: domains
  rrdatasRefs:
    - kind: ComputeAddress
      name: traefik-ingress
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik-kfirs-com
spec:
  secretName: traefik-kfirs-com-tls
  issuerRef:
    kind: ClusterIssuer
    name: google-clouddns
  dnsNames:
    - traefik.kfirs.com
---
apiVersion: dns.cnrm.cloud.google.com/v1beta1
kind: DNSRecordSet
metadata:
  name: oauth-kfirs-com-a
spec:
  name: oauth.kfirs.com.
  type: CNAME
  ttl: 300
  managedZoneRef:
    name: kfirs-com
    namespace: domains
  rrdatas:
    - traefik.kfirs.com.
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: oauth-kfirs-com
spec:
  secretName: oauth-kfirs-com-tls
  issuerRef:
    kind: ClusterIssuer
    name: google-clouddns
  dnsNames:
    - oauth.kfirs.com
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: dashboard-http
spec:
  entryPoints: [web]
  routes:
    - kind: Rule
      match: Host(`traefik.kfirs.com`)
      middlewares:
        - name: redirect-to-https
          namespace: traefik
      services:
        - kind: TraefikService
          name: api@internal
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: dashboard-https
spec:
  entryPoints: [websecure]
  routes:
    - kind: Rule
      match: Host(`traefik.kfirs.com`)
      services:
        - kind: TraefikService
          name: api@internal
      # TODO: enable forward auth with Google OIDC, via the "middlewares: []"
  tls:
    secretName: traefik-kfirs-com-tls
