apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-operator
  namespace: default
spec:
  dependsOn:
    - name: config-connector-manager
  interval: 5m
  path: platform/cert-manager/operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-issuer
  namespace: default
spec:
  dependsOn:
    - name: cert-manager-operator
  interval: 5m
  path: platform/cert-manager/issuer
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
