apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-operator
  namespace: default
spec:
  force: true
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      namespace: cert-manager
      name: cert-manager
    - apiVersion: iam.cnrm.cloud.google.com/v1beta1
      kind: IAMServiceAccount
      name: cert-manager
    - apiVersion: iam.cnrm.cloud.google.com/v1beta1
      kind: IAMPolicyMember
      name: cert-manager-dns-admin
    - apiVersion: iam.cnrm.cloud.google.com/v1beta1
      kind: IAMPolicyMember
      name: cert-manager-ksa-link
  interval: 5m
  path: platform/cert-manager/operator
  prune: true
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 15m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-issuer
  namespace: default
spec:
  dependsOn:
    - name: cert-manager-operator
  force: true
  healthChecks:
    - apiVersion: cert-manager.io/v1
      kind: ClusterIssuer
      name: google-clouddns
    - apiVersion: cert-manager.io/v1
      kind: ClusterIssuer
      name: google-clouddns-prod
  interval: 5m
  path: platform/cert-manager/issuer
  prune: true
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 15m
  wait: true
