apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: config-connector-operator
  namespace: default
spec:
  interval: 5m
  path: platform/config-connector/operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
  patches:
    - patch: |
        - op: replace
          path: /spec/template/spec/containers/0/resources/requests/cpu
          value: 50m
        - op: add
          path: /spec/template/spec/containers/0/resources/limits/cpu
          value: 50m
      target:
        kind: StatefulSet
        namespace: configconnector-operator-system
        name: configconnector-operator
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: config-connector-manager
  namespace: default
spec:
  dependsOn:
    - name: config-connector-operator
  interval: 5m
  path: platform/config-connector/manager
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
