apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: config-connector-operator
  namespace: default
spec:
  force: true
  healthChecks:
    - apiVersion: apps/v1
      kind: StatefulSet
      name: configconnector-operator
      namespace: configconnector-operator-system
  interval: 5m
  path: platform/config-connector/operator
  prune: true
  retryInterval: 1m
  patches:
    - patch: |
        - op: replace
          path: /spec/template/spec/containers/0/resources/requests/cpu
          value: 50m
        - op: add
          path: /spec/template/spec/containers/0/resources/limits/cpu
          value: 50m
      target:
        kind: StatefulSet
        namespace: configconnector-operator-system
        name: configconnector-operator
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: config-connector-manager
  namespace: default
spec:
  force: true
  healthChecks:
    - apiVersion: core.cnrm.cloud.google.com/v1beta1
      kind: ConfigConnector
      name: configconnector.core.cnrm.cloud.google.com
  interval: 5m
  path: platform/config-connector/manager
  prune: true
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 5m
