apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dns
  namespace: default
spec:
  dependsOn:
    - name: config-connector-manager
  force: true
  healthChecks:
    - apiVersion: dns.cnrm.cloud.google.com/v1beta1
      kind: DNSManagedZone
      namespace: dns
      name: kfirfamily-com
    - apiVersion: dns.cnrm.cloud.google.com/v1beta1
      kind: DNSManagedZone
      namespace: dns
      name: kfirs-com
    - apiVersion: dns.cnrm.cloud.google.com/v1beta1
      kind: DNSManagedZone
      namespace: dns
      name: yellow-mint-com
    - apiVersion: dns.cnrm.cloud.google.com/v1beta1
      kind: DNSRecordSet
      namespace: dns
      name: art-cbt-kfirs-com-cname
    - apiVersion: dns.cnrm.cloud.google.com/v1beta1
      kind: DNSRecordSet
      namespace: dns
      name: kfirfamily-com-mx
    - apiVersion: dns.cnrm.cloud.google.com/v1beta1
      kind: DNSRecordSet
      namespace: dns
      name: kfirs-com-apex
    - apiVersion: dns.cnrm.cloud.google.com/v1beta1
      kind: DNSRecordSet
      namespace: dns
      name: kfirs-com-mx
    - apiVersion: dns.cnrm.cloud.google.com/v1beta1
      kind: DNSRecordSet
      namespace: dns
      name: kfirs-com-txt
    - apiVersion: dns.cnrm.cloud.google.com/v1beta1
      kind: DNSRecordSet
      namespace: dns
      name: www-art-cbt-kfirs-com-cname
    - apiVersion: dns.cnrm.cloud.google.com/v1beta1
      kind: DNSRecordSet
      namespace: dns
      name: www-kfirs-com-cname
    - apiVersion: dns.cnrm.cloud.google.com/v1beta1
      kind: DNSRecordSet
      namespace: dns
      name: www-yellow-mint-com-cname
    - apiVersion: dns.cnrm.cloud.google.com/v1beta1
      kind: DNSRecordSet
      namespace: dns
      name: yellow-mint-com-apex
    - apiVersion: dns.cnrm.cloud.google.com/v1beta1
      kind: DNSRecordSet
      namespace: dns
      name: yellow-mint-com-mx
    - apiVersion: dns.cnrm.cloud.google.com/v1beta1
      kind: DNSRecordSet
      namespace: dns
      name: yellow-mint-com-txt
  interval: 5m
  path: platform/dns
  prune: true
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 15m
  wait: true
