apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dns
  namespace: default
spec:
  force: true
  healthChecks:
    - apiVersion: dns.cnrm.cloud.google.com/v1beta1
      kind: DNSManagedZone
      name: kfirfamily-com
      namespace: dns
    - apiVersion: dns.cnrm.cloud.google.com/v1beta1
      kind: DNSManagedZone
      name: kfirs-com
      namespace: dns
    - apiVersion: dns.cnrm.cloud.google.com/v1beta1
      kind: DNSManagedZone
      name: yellow-mint-com
      namespace: dns
    - apiVersion: dns.cnrm.cloud.google.com/v1beta1
      kind: DNSRecordSet
      name: art-cbt-kfirs-com-cname
      namespace: dns
    - apiVersion: dns.cnrm.cloud.google.com/v1beta1
      kind: DNSRecordSet
      name: kfirfamily-com-mx
      namespace: dns
    - apiVersion: dns.cnrm.cloud.google.com/v1beta1
      kind: DNSRecordSet
      name: kfirs-com-apex
      namespace: dns
    - apiVersion: dns.cnrm.cloud.google.com/v1beta1
      kind: DNSRecordSet
      name: kfirs-com-mx
      namespace: dns
    - apiVersion: dns.cnrm.cloud.google.com/v1beta1
      kind: DNSRecordSet
      name: kfirs-com-txt
      namespace: dns
    - apiVersion: dns.cnrm.cloud.google.com/v1beta1
      kind: DNSRecordSet
      name: www-art-cbt-kfirs-com-cname
      namespace: dns
    - apiVersion: dns.cnrm.cloud.google.com/v1beta1
      kind: DNSRecordSet
      name: www-kfirs-com-cname
      namespace: dns
    - apiVersion: dns.cnrm.cloud.google.com/v1beta1
      kind: DNSRecordSet
      name: www-yellow-mint-com-cname
      namespace: dns
    - apiVersion: dns.cnrm.cloud.google.com/v1beta1
      kind: DNSRecordSet
      name: yellow-mint-com-apex
      namespace: dns
    - apiVersion: dns.cnrm.cloud.google.com/v1beta1
      kind: DNSRecordSet
      name: yellow-mint-com-mx
      namespace: dns
    - apiVersion: dns.cnrm.cloud.google.com/v1beta1
      kind: DNSRecordSet
      name: yellow-mint-com-txt
      namespace: dns
  interval: 5m
  path: platform/dns
  prune: true
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 5m
