apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets
  namespace: default
spec:
  force: true
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      namespace: external-secrets
      name: external-secrets
    - apiVersion: iam.cnrm.cloud.google.com/v1beta1
      kind: IAMServiceAccount
      namespace: external-secrets
      name: gke-external-secrets
    - apiVersion: iam.cnrm.cloud.google.com/v1beta1
      kind: IAMPolicyMember
      namespace: external-secrets
      name: gke-external-secrets-ksa-link
    - apiVersion: iam.cnrm.cloud.google.com/v1beta1
      kind: IAMPolicyMember
      namespace: external-secrets
      name: gke-external-secrets-secret-viewer
    - apiVersion: iam.cnrm.cloud.google.com/v1beta1
      kind: IAMPolicyMember
      namespace: external-secrets
      name: gke-external-secrets-secret-accessor
    - apiVersion: external-secrets.io/v1beta1
      kind: ClusterSecretStore
      name: gcp-secret-manager
  interval: 5m
  path: platform/external-secrets
  prune: true
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 15m
  wait: true
