apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-webhook
  namespace: default
spec:
  dependsOn:
    - name: cert-manager-issuer
    - name: config-connector-manager
    - name: dns
    - name: flux-system
      namespace: flux-system
    - name: traefik
  interval: 5m
  path: platform/flux-webhook
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
