apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-webhook
  namespace: default
spec:
  force: true
  healthChecks:
    - apiVersion: cert-manager.io/v1
      kind: Certificate
      name: webhook-flux-kfirs-com
      namespace: flux-system
    - apiVersion: dns.cnrm.cloud.google.com/v1beta1
      kind: DNSRecordSet
      name: webhook-flux-kfirs-com-a
      namespace: flux-system
    - apiVersion: iam.cnrm.cloud.google.com/v1beta1
      kind: IAMServiceAccount
      name: flux-notification-controller
      namespace: flux-system
    - apiVersion: iam.cnrm.cloud.google.com/v1beta1
      kind: IAMPolicyMember
      name: flux-notification-controller-ksa-link
      namespace: flux-system
    - apiVersion: iam.cnrm.cloud.google.com/v1beta1
      kind: IAMPolicyMember
      name: flux-notification-controller-secret-viewer
      namespace: flux-system
    - apiVersion: iam.cnrm.cloud.google.com/v1beta1
      kind: IAMPolicyMember
      name: flux-notification-controller-secret-accessor
      namespace: flux-system
    - apiVersion: notification.toolkit.fluxcd.io/v1
      kind: Receiver
      name: delivery
      namespace: flux-system
    - apiVersion: external-secrets.io/v1beta1
      kind: ExternalSecret
      name: fluxcd-github-webhook-secret
      namespace: flux-system
  interval: 5m
  path: platform/flux-webhook
  prune: true
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 5m
