apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: playwright
  namespace: default
spec:
  force: true
  healthChecks:
    - apiVersion: cert-manager.io/v1
      kind: Certificate
      name: playwright
      namespace: playwright
    - apiVersion: apps/v1
      kind: Deployment
      name: playwright
      namespace: playwright
    - apiVersion: dns.cnrm.cloud.google.com/v1beta1
      kind: DNSRecordSet
      name: playwright-a-record
      namespace: playwright
    - apiVersion: iam.cnrm.cloud.google.com/v1beta1
      kind: IAMServiceAccount
      name: playwright-server
      namespace: playwright
    - apiVersion: iam.cnrm.cloud.google.com/v1beta1
      kind: IAMPolicyMember
      name: playwright-server-ksa-link
      namespace: playwright
    - apiVersion: iam.cnrm.cloud.google.com/v1beta1
      kind: IAMPolicyMember
      name: playwright-server-storage-object-viewer
      namespace: playwright
    - apiVersion: iam.cnrm.cloud.google.com/v1beta1
      kind: IAMServiceAccount
      name: playwright-uploader
      namespace: playwright
    - apiVersion: iam.cnrm.cloud.google.com/v1beta1
      kind: IAMPolicyMember
      name: playwright-uploader-oidc-link
      namespace: playwright
    - apiVersion: iam.cnrm.cloud.google.com/v1beta1
      kind: IAMPolicyMember
      name: playwright-uploader-storage-object-creator
      namespace: playwright
    - apiVersion: iam.cnrm.cloud.google.com/v1beta1
      kind: IAMPolicyMember
      name: playwright-uploader-storage-object-viewer
      namespace: playwright
  interval: 5m
  path: platform/playwright
  prune: true
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 5m
