apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: traefik
  namespace: default
spec:
  dependsOn:
    - name: cert-manager-issuer
    - name: config-connector-manager
    - name: dns
  force: true
  healthChecks:
    - apiVersion: cert-manager.io/v1
      kind: Certificate
      namespace: traefik
      name: traefik-kfirs-com
    - apiVersion: compute.cnrm.cloud.google.com/v1beta1
      kind: ComputeAddress
      namespace: traefik
      name: gke-ingress
    - apiVersion: dns.cnrm.cloud.google.com/v1beta1
      kind: DNSRecordSet
      namespace: traefik
      name: traefik-kfirs-com-a
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      namespace: traefik
      name: traefik
  interval: 5m
  path: platform/traefik
  prune: true
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 15m
  wait: true
