apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: traefik
  namespace: default
spec:
  force: true
  healthChecks:
    - apiVersion: cert-manager.io/v1
      kind: Certificate
      name: traefik-kfirs-com
      namespace: traefik
    - apiVersion: compute.cnrm.cloud.google.com/v1beta1
      kind: ComputeAddress
      name: gke-ingress
      namespace: traefik
    - apiVersion: dns.cnrm.cloud.google.com/v1beta1
      kind: DNSRecordSet
      name: traefik-kfirs-com-a
      namespace: traefik
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: traefik
      namespace: traefik
  interval: 5m
  path: platform/traefik
  prune: true
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 5m
