apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dependabot-npm-and-y-sdk-1-0-14
images:
  - name: ghcr.io/arikkfir/greenstar/backend
    newTag: 84e396fc63a45f1f665264a287d34e5738b120db
  - name: ghcr.io/arikkfir/greenstar/frontend
    newTag: 84e396fc63a45f1f665264a287d34e5738b120db
  - name: ghcr.io/arikkfir/greenstar/migrations
    newTag: 84e396fc63a45f1f665264a287d34e5738b120db
  - name: ghcr.io/arikkfir/greenstar/neo4j
    newTag: 84e396fc63a45f1f665264a287d34e5738b120db
patches: []
resources:
  - ../main
