apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: secrets-store-csi-driver
spec:
  interval: 5m
  url: https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: secrets-store-csi-driver
spec:
  interval: 5m
  timeout: 5m
  releaseName: csi-secrets-store
  targetNamespace: kube-system
  chart:
    spec:
      chart: secrets-store-csi-driver
      sourceRef:
        kind: HelmRepository
        name: secrets-store-csi-driver
  values:
    syncSecret:
      enabled: true
    enableSecretRotation: true
    logFormatJSON: true
    linux:
      nodeSelector:
        gke.kfirs.com/purpose: workloads
      tolerations:
        - effect: NoExecute
          key: gke.kfirs.com/purpose
          operator: Equal
          value: workloads
