apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
patches:
  - patch: |
      - op: add
        path: /metadata/annotations/cnrm.cloud.google.com~1project-id
        value: arikkfir
    target:
      kind: Namespace
      name: flux-system
  - patch: |
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --concurrent=10
      - op: add
        path: /spec/template/spec/nodeSelector
        value:
          node.kfirs.com/role: work
      - op: add
        path: /spec/template/spec/tolerations
        value:
          - effect: NoExecute
            key: node.kfirs.com/role
            operator: Equal
            value: work
    target:
      kind: Deployment
      labelSelector: app.kubernetes.io/part-of=flux
  - patch: |
      - op: replace
        path: /spec/template/spec/containers/0/args/2
        value: --log-level=warn
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --requeue-dependency=3s
    target:
      kind: Deployment
      name: '(source-controller|helm-controller|kustomize-controller)'
  - patch: |
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --feature-gates=AllowDNSLookups=true,DetectDrift=true,OOMWatch=true
    target:
      kind: Deployment
      name: helm-controller
  - patch: |
      - op: add
        path: /metadata/annotations
        value:
          iam.gke.io/gcp-service-account: flux-notification-controller@arikkfir.iam.gserviceaccount.com
    target:
      group: ""
      version: v1
      kind: ServiceAccount
      labelSelector: app.kubernetes.io/component=notification-controller
  - patch: |
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: 100m
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: 100m
    target:
      group: apps
      version: v1
      kind: Deployment
      name: helm-controller
  - patch: |
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: ghcr.io/arikkfir/fluxcd/kustomize-controller:bdbd71a904538fb7ea03b521e5fd21bf587f83da
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: 100m
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: 100m
    target:
      group: apps
      version: v1
      kind: Deployment
      name: kustomize-controller
  - patch: |
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: 50m
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: 50m
    target:
      group: apps
      version: v1
      kind: Deployment
      name: notification-controller
  - patch: |
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: 50m
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: 50m
    target:
      group: apps
      version: v1
      kind: Deployment
      name: source-controller
