apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
patches:
  - patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: all
      spec:
        template:
          spec:
            nodeSelector:
              gke.kfirs.com/purpose: workloads
            tolerations:
              - effect: NoExecute
                key: node.kfirs.com/role
                operator: Equal
                value: work
    target:
      kind: Deployment
      labelSelector: app.kubernetes.io/part-of=flux
