apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fix-backend-gcp-deployment
resources:
  - ../_commons/namespace.yaml
  - ../_commons/echo-server.yaml
  - https://github.com/arikkfir/greenstar//deploy/cluster?ref=fix-backend-gcp-deployment
