apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dependabot-npm-and-y-al-5-14-10
images:
  - name: ghcr.io/arikkfir/greenstar/backend
    newTag: b47ba255c40dfbfe83c879e2abea26867430cd32
  - name: ghcr.io/arikkfir/greenstar/frontend
    newTag: b47ba255c40dfbfe83c879e2abea26867430cd32
  - name: ghcr.io/arikkfir/greenstar/migrations
    newTag: b47ba255c40dfbfe83c879e2abea26867430cd32
  - name: ghcr.io/arikkfir/greenstar/neo4j
    newTag: b47ba255c40dfbfe83c879e2abea26867430cd32
patches: []
resources:
  - ../main
