apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dependabot-docker-frontend-node-20-6-0
images:
  - name: ghcr.io/arikkfir/greenstar/backend
    newTag: 78b9149db40dd249936145c067475b958b91f91c
  - name: ghcr.io/arikkfir/greenstar/frontend
    newTag: 78b9149db40dd249936145c067475b958b91f91c
  - name: ghcr.io/arikkfir/greenstar/migrations
    newTag: 78b9149db40dd249936145c067475b958b91f91c
  - name: ghcr.io/arikkfir/greenstar/neo4j
    newTag: 78b9149db40dd249936145c067475b958b91f91c
patches: []
resources:
  - ../main
