apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dependabot-docker-frontend-node-20-6-0
images:
  - name: ghcr.io/arikkfir/greenstar/backend
    newTag: a3acf5104bd96d089bb185a40eff1efeb73c04a2
  - name: ghcr.io/arikkfir/greenstar/frontend
    newTag: a3acf5104bd96d089bb185a40eff1efeb73c04a2
  - name: ghcr.io/arikkfir/greenstar/migrations
    newTag: a3acf5104bd96d089bb185a40eff1efeb73c04a2
  - name: ghcr.io/arikkfir/greenstar/neo4j
    newTag: a3acf5104bd96d089bb185a40eff1efeb73c04a2
patches: []
resources:
  - ../main
