apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dependabot-docker-frontend-node-20-6-0
images:
  - name: ghcr.io/arikkfir/greenstar/backend
    newTag: b5b2e676106c38fc79de32bd532699e6463a97e0
  - name: ghcr.io/arikkfir/greenstar/frontend
    newTag: b5b2e676106c38fc79de32bd532699e6463a97e0
  - name: ghcr.io/arikkfir/greenstar/migrations
    newTag: b5b2e676106c38fc79de32bd532699e6463a97e0
  - name: ghcr.io/arikkfir/greenstar/neo4j
    newTag: b5b2e676106c38fc79de32bd532699e6463a97e0
patches: []
resources:
  - ../main
