apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dependabot-github-actions-actions-checkout-4
images:
  - name: ghcr.io/arikkfir/greenstar/backend
    newTag: b2ac5f9911b470a1e05d08387201fb543b78b581
  - name: ghcr.io/arikkfir/greenstar/frontend
    newTag: b2ac5f9911b470a1e05d08387201fb543b78b581
  - name: ghcr.io/arikkfir/greenstar/migrations
    newTag: b2ac5f9911b470a1e05d08387201fb543b78b581
  - name: ghcr.io/arikkfir/greenstar/neo4j
    newTag: b2ac5f9911b470a1e05d08387201fb543b78b581
patches: []
resources:
  - ../main
