apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dependabot-npm-and-yarn-frontend-descope-react-sdk-1-0-14
images:
  - name: ghcr.io/arikkfir/greenstar/backend
    newTag: 93328ef2428fe1a83ed5e2d9d4ccd6ddf4e85030
  - name: ghcr.io/arikkfir/greenstar/frontend
    newTag: 93328ef2428fe1a83ed5e2d9d4ccd6ddf4e85030
  - name: ghcr.io/arikkfir/greenstar/migrations
    newTag: 93328ef2428fe1a83ed5e2d9d4ccd6ddf4e85030
  - name: ghcr.io/arikkfir/greenstar/neo4j
    newTag: 93328ef2428fe1a83ed5e2d9d4ccd6ddf4e85030
patches:
  - patch: |
      - op: replace
        path: /spec/replicas
        value: 0
    target:
      group: apps
      version: v1
      kind: Deployment
  - patch: |
      - op: replace
        path: /spec/values/replicaCount
        value: 0
    target:
      group: helm.toolkit.fluxcd.io
      version: v2beta1
      kind: HelmRelease
  - patch: |
      - op: replace
        path: /spec/replicas
        value: 0
    target:
      group: apps
      version: v1
      kind: StatefulSet
  - patch: |
      - op: replace
        path: /spec/suspend
        value: true
    target:
      group: batch
      version: v1
      kind: Job
resources:
  - ../main
