apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dependabot-npm-and-y-t-parser-6
images:
  - name: ghcr.io/arikkfir/greenstar/backend
    newTag: 108e2207bfde86ed0a1a934ab25c2eeb045f5b63
  - name: ghcr.io/arikkfir/greenstar/frontend
    newTag: 108e2207bfde86ed0a1a934ab25c2eeb045f5b63
  - name: ghcr.io/arikkfir/greenstar/migrations
    newTag: 108e2207bfde86ed0a1a934ab25c2eeb045f5b63
  - name: ghcr.io/arikkfir/greenstar/neo4j
    newTag: 108e2207bfde86ed0a1a934ab25c2eeb045f5b63
patches:
  - patch: |
      - op: replace
        path: /spec/replicas
        value: 0
    target:
      group: apps
      version: v1
      kind: Deployment
  - patch: |
      - op: replace
        path: /spec/values/replicaCount
        value: 0
    target:
      group: helm.toolkit.fluxcd.io
      version: v2beta1
      kind: HelmRelease
  - patch: |
      - op: replace
        path: /spec/replicas
        value: 0
    target:
      group: apps
      version: v1
      kind: StatefulSet
  - patch: |
      - op: replace
        path: /spec/suspend
        value: true
    target:
      group: batch
      version: v1
      kind: Job
resources:
  - ../main
