apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: upgrade-backend-go-dependencies
images:
  - name: ghcr.io/arikkfir/greenstar/backend
    newTag: 45b5d2d4c4055efdd7f40c9086eeb151f797df51
  - name: ghcr.io/arikkfir/greenstar/frontend
    newTag: 45b5d2d4c4055efdd7f40c9086eeb151f797df51
  - name: ghcr.io/arikkfir/greenstar/migrations
    newTag: 45b5d2d4c4055efdd7f40c9086eeb151f797df51
  - name: ghcr.io/arikkfir/greenstar/neo4j
    newTag: 45b5d2d4c4055efdd7f40c9086eeb151f797df51
patches: []
resources:
  - ../main
