apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dependabot-docker-mi-enterprise
images:
  - name: ghcr.io/arikkfir/greenstar/backend
    newTag: df9fee638ca6dc8fbbd0761112c7e880bd714938
  - name: ghcr.io/arikkfir/greenstar/frontend
    newTag: df9fee638ca6dc8fbbd0761112c7e880bd714938
  - name: ghcr.io/arikkfir/greenstar/migrations
    newTag: df9fee638ca6dc8fbbd0761112c7e880bd714938
  - name: ghcr.io/arikkfir/greenstar/neo4j
    newTag: df9fee638ca6dc8fbbd0761112c7e880bd714938
patches: []
resources:
  - ../main
