apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: provide-http-cors-allowed-origins-to-backend
resources:
  - ../_commons/namespace.yaml
  - ../_commons/echo-server.yaml
  - https://github.com/arikkfir/greenstar//deploy/cluster?ref=provide-http-cors-allowed-origins-to-backend
