apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dependabot-go-module-dis-1-0-18
images:
  - name: ghcr.io/arikkfir/greenstar/backend
    newTag: 2638d4c0bb3b3ceb0480ea5797e85775efbdcb71
  - name: ghcr.io/arikkfir/greenstar/frontend
    newTag: 2638d4c0bb3b3ceb0480ea5797e85775efbdcb71
  - name: ghcr.io/arikkfir/greenstar/migrations
    newTag: 2638d4c0bb3b3ceb0480ea5797e85775efbdcb71
  - name: ghcr.io/arikkfir/greenstar/neo4j
    newTag: 2638d4c0bb3b3ceb0480ea5797e85775efbdcb71
patches: []
resources:
  - ../main
