apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: add-e2e-testing
resources:
  - ../_commons/namespace.yaml
  - ../_commons/echo-server.yaml
  - ../_commons/greenstar
patches:
  - patch: |
      - op: replace
        path: /spec/replicas
        value: 0
    target:
      group: apps
      version: v1
      kind: Deployment
  - patch: |
      - op: replace
        path: /spec/values/replicaCount
        value: 0
    target:
      group: helm.toolkit.fluxcd.io
      version: v2beta1
      kind: HelmRelease
