apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: add-e2e-testing
images:
  - name: ghcr.io/arikkfir/greenstar/backend
    newTag: edcfc7885af37cc205237e128b0ee4ffc881ed1c
  - name: ghcr.io/arikkfir/greenstar/frontend
    newTag: edcfc7885af37cc205237e128b0ee4ffc881ed1c
  - name: ghcr.io/arikkfir/greenstar/migrations
    newTag: edcfc7885af37cc205237e128b0ee4ffc881ed1c
  - name: ghcr.io/arikkfir/greenstar/neo4j
    newTag: edcfc7885af37cc205237e128b0ee4ffc881ed1c
patches: []
resources:
  - ../main
