apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: add-e2e-testing
images:
  - name: ghcr.io/arikkfir/greenstar/backend
    newTag: 9a63c208a029b6fe18d70ca19191bedd98e05144
  - name: ghcr.io/arikkfir/greenstar/frontend
    newTag: 9a63c208a029b6fe18d70ca19191bedd98e05144
  - name: ghcr.io/arikkfir/greenstar/migrations
    newTag: 9a63c208a029b6fe18d70ca19191bedd98e05144
  - name: ghcr.io/arikkfir/greenstar/neo4j
    newTag: 9a63c208a029b6fe18d70ca19191bedd98e05144
patches: []
resources:
  - ../main
