apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: e2e-initial-tests
images:
  - name: ghcr.io/arikkfir/greenstar/backend
    newTag: a2550a96b64eac20137404c1496fd7d752b578fb
  - name: ghcr.io/arikkfir/greenstar/frontend
    newTag: a2550a96b64eac20137404c1496fd7d752b578fb
  - name: ghcr.io/arikkfir/greenstar/migrations
    newTag: a2550a96b64eac20137404c1496fd7d752b578fb
  - name: ghcr.io/arikkfir/greenstar/neo4j
    newTag: a2550a96b64eac20137404c1496fd7d752b578fb
patches: []
resources:
  - ../main
