apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: e2e-initial-tests
images:
  - name: ghcr.io/arikkfir/greenstar/backend
    newTag: 5a264fd00f6515d0d7745e04c9bd7b9d49bfa619
  - name: ghcr.io/arikkfir/greenstar/frontend
    newTag: 5a264fd00f6515d0d7745e04c9bd7b9d49bfa619
  - name: ghcr.io/arikkfir/greenstar/migrations
    newTag: 5a264fd00f6515d0d7745e04c9bd7b9d49bfa619
  - name: ghcr.io/arikkfir/greenstar/neo4j
    newTag: 5a264fd00f6515d0d7745e04c9bd7b9d49bfa619
patches: []
resources:
  - ../main
