apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: e2e-initial-tests
images:
  - name: ghcr.io/arikkfir/greenstar/backend
    newTag: 4a706401aa9a004a206486f17a674c834cf91574
  - name: ghcr.io/arikkfir/greenstar/frontend
    newTag: 4a706401aa9a004a206486f17a674c834cf91574
  - name: ghcr.io/arikkfir/greenstar/migrations
    newTag: 4a706401aa9a004a206486f17a674c834cf91574
  - name: ghcr.io/arikkfir/greenstar/neo4j
    newTag: 4a706401aa9a004a206486f17a674c834cf91574
patches:
  - patch: |
      - op: replace
        path: /spec/replicas
        value: 0
    target:
      group: apps
      version: v1
      kind: Deployment
  - patch: |
      - op: replace
        path: /spec/values/replicaCount
        value: 0
    target:
      group: helm.toolkit.fluxcd.io
      version: v2beta1
      kind: HelmRelease
  - patch: |
      - op: replace
        path: /spec/replicas
        value: 0
    target:
      group: apps
      version: v1
      kind: StatefulSet
resources:
  - ../main
