apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dependabot-go-module--sdk-1-5-6
images:
  - name: ghcr.io/arikkfir/greenstar/backend
    newTag: 2a6f5016356cdd0d8343ade3f4b93de4392255a3
  - name: ghcr.io/arikkfir/greenstar/frontend
    newTag: 2a6f5016356cdd0d8343ade3f4b93de4392255a3
  - name: ghcr.io/arikkfir/greenstar/migrations
    newTag: 2a6f5016356cdd0d8343ade3f4b93de4392255a3
  - name: ghcr.io/arikkfir/greenstar/neo4j
    newTag: 2a6f5016356cdd0d8343ade3f4b93de4392255a3
patches: []
resources:
  - ../main
