apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: frontend
resources:
  - rbac.yaml
  - service.yaml
  - deployment.yaml
configurations:
  - kustomizeconfig.yaml
