apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: "dependabot-github-ac-ons-auth-2"
commonAnnotations:
  kfirs.com/branch: "dependabot/github_actions/google-github-actions/auth-2"
  kfirs.com/environment: "dependabot-github-ac-ons-auth-2"
resources:
  - ../main
patches:
  # Patch the "namespace" object's name to this environment's name
  - patch: |-
      - op: replace
        path: /metadata/name
        value: "dependabot-github-ac-ons-auth-2"
    target:
      group: ""
      version: v1
      kind: Namespace
  # Patch all FluxCD "Kustomization" objects' target namespace property to this environment's name
  - patch: |
      - op: replace
        path: /spec/targetNamespace
        value: "dependabot-github-ac-ons-auth-2"
    target:
      group: kustomize.toolkit.fluxcd.io
      version: v1
      kind: Kustomization
  # Patch all FluxCD "Kustomization" objects' substitution map to reflect this environment's name
  - patch: |
      - op: replace
        path: /spec/postBuild/substitute/deploy_environment
        value: "dependabot-github-ac-ons-auth-2"
    target:
      group: kustomize.toolkit.fluxcd.io
      version: v1
      kind: Kustomization
  # Patch all FluxCD "Kustomization" objects to use the ACME Staging server for certificates
  - patch: |
      - op: add
        path: /spec/patches/-
        value:
          target:
            group: cert-manager.io
            version: v1
            kind: Certificate
          patch: |-
            - op: replace
              path: /spec/issuerRef/name
              value: google-clouddns
    target:
      group: kustomize.toolkit.fluxcd.io
      version: v1
      kind: Kustomization
  # Patch the GreenSTAR alert to use the correct namespace based on this environment's name
  - patch: |
      - op: replace
        path: /spec/eventSources/0/namespace
        value: "dependabot-github-ac-ons-auth-2"
    target:
      group: notification.toolkit.fluxcd.io
      version: v1beta2
      kind: Alert
      name: greenstar
  # Fix health checks of the greenstar kustomization
  - patch: |
      - op: replace
        path: /spec/healthChecks/0/namespace
        value: "dependabot-github-ac-ons-auth-2"
      - op: replace
        path: /spec/healthChecks/1/namespace
        value: "dependabot-github-ac-ons-auth-2"
      - op: replace
        path: /spec/healthChecks/2/namespace
        value: "dependabot-github-ac-ons-auth-2"
      - op: replace
        path: /spec/healthChecks/3/namespace
        value: "dependabot-github-ac-ons-auth-2"
      - op: replace
        path: /spec/healthChecks/4/namespace
        value: "dependabot-github-ac-ons-auth-2"
      - op: replace
        path: /spec/healthChecks/5/namespace
        value: "dependabot-github-ac-ons-auth-2"
    target:
      group: kustomize.toolkit.fluxcd.io
      version: v1
      kind: Kustomization
      name: greenstar
  - patch: |
      - op: replace
        path: /spec/ref/branch
        value: "dependabot/github_actions/google-github-actions/auth-2"
    target:
      group: source.toolkit.fluxcd.io
      version: v1
      kind: GitRepository
      name: "greenstar"
