apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: backend
  name: backend
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/component: backend
  type: ClusterIP
