apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dependabot-npm-and-y-ient-3-8-3
images:
  - name: ghcr.io/arikkfir/greenstar/backend
    newTag: f26a6503726e661efad045ad8cb9a43ad1b26778
  - name: ghcr.io/arikkfir/greenstar/frontend
    newTag: f26a6503726e661efad045ad8cb9a43ad1b26778
  - name: ghcr.io/arikkfir/greenstar/migrations
    newTag: f26a6503726e661efad045ad8cb9a43ad1b26778
  - name: ghcr.io/arikkfir/greenstar/neo4j
    newTag: f26a6503726e661efad045ad8cb9a43ad1b26778
patches:
  - patch: |
      - op: replace
        path: /spec/replicas
        value: 0
    target:
      group: apps
      version: v1
      kind: Deployment
  - patch: |
      - op: replace
        path: /spec/values/replicaCount
        value: 0
    target:
      group: helm.toolkit.fluxcd.io
      version: v2beta1
      kind: HelmRelease
  - patch: |
      - op: replace
        path: /spec/replicas
        value: 0
    target:
      group: apps
      version: v1
      kind: StatefulSet
  - patch: |
      - op: replace
        path: /spec/suspend
        value: true
    target:
      group: batch
      version: v1
      kind: Job
resources:
  - ../main
