apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dependabot-npm-and-y-ient-3-8-3
images:
  - name: ghcr.io/arikkfir/greenstar/backend
    newTag: c87683a00a4afd1a3da17bc73170052a61b744b1
  - name: ghcr.io/arikkfir/greenstar/frontend
    newTag: c87683a00a4afd1a3da17bc73170052a61b744b1
  - name: ghcr.io/arikkfir/greenstar/migrations
    newTag: c87683a00a4afd1a3da17bc73170052a61b744b1
  - name: ghcr.io/arikkfir/greenstar/neo4j
    newTag: c87683a00a4afd1a3da17bc73170052a61b744b1
patches: []
resources:
  - ../main
