apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dependabot-npm-and-y-ient-3-8-3
images:
  - name: ghcr.io/arikkfir/greenstar/backend
    newTag: ae4b3b4c3871f2837318aed006e36f078521cd7d
  - name: ghcr.io/arikkfir/greenstar/frontend
    newTag: ae4b3b4c3871f2837318aed006e36f078521cd7d
  - name: ghcr.io/arikkfir/greenstar/migrations
    newTag: ae4b3b4c3871f2837318aed006e36f078521cd7d
  - name: ghcr.io/arikkfir/greenstar/neo4j
    newTag: ae4b3b4c3871f2837318aed006e36f078521cd7d
patches:
  - patch: |
      - op: replace
        path: /spec/replicas
        value: 0
    target:
      group: apps
      version: v1
      kind: Deployment
  - patch: |
      - op: replace
        path: /spec/values/replicaCount
        value: 0
    target:
      group: helm.toolkit.fluxcd.io
      version: v2beta1
      kind: HelmRelease
  - patch: |
      - op: replace
        path: /spec/replicas
        value: 0
    target:
      group: apps
      version: v1
      kind: StatefulSet
resources:
  - ../main
