apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keda
  namespace: keda
spec:
  interval: 5m
  chart:
    spec:
      chart: keda
      version: 2.11.2
      sourceRef:
        kind: HelmRepository
        name: traefik
  values:
    webhooks:
      failurePolicy: Fail
    logging:
      operator:
        format: json
      webhooks:
        format: json
    resources:
      operator:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 100Mi
      metricServer:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 100Mi
      webhooks:
        limits:
          cpu: 50m
          memory: 100Mi
        requests:
          cpu: 10m
          memory: 10Mi
    nodeSelector:
      node.kfirs.com/role: work
    tolerations:
      - effect: NoExecute
        key: node.kfirs.com/role
        operator: Equal
        value: work
    prometheus:
      metricServer:
        enabled: true
      operator:
        enabled: true
        port: 8080
      webhooks:
        enabled: true
