apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: env-adjust-nginx-for-htmlo5
  namespace: default
spec:
  dependsOn:
    - name: cert-manager-issuer
    - name: config-connector-manager
    - name: default
    - name: dns
    - name: external-secrets
    - name: traefik
  interval: 5m
  path: environments/adjust-nginx-for-htmlo5
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
  postBuild:
    substitute:
      flux_environment: adjust-nginx-for-htmlo5
---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: arikkfir
  name: adjust-nginx-for-htmlo5
