apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: env-main
  namespace: default
spec:
  dependsOn:
    - name: cert-manager-issuer
    - name: config-connector-manager
    - name: default
    - name: dns
    - name: external-secrets
    - name: traefik
  interval: 5m
  path: environments/main
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
  postBuild:
    substitute:
      flux_environment: main
