apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: env-move-concurrency-to-workflow-level
  namespace: default
spec:
  dependsOn:
    - name: cert-manager-issuer
    - name: config-connector-manager
    - name: default
    - name: dns
    - name: external-secrets
    - name: traefik
  interval: 5m
  path: environments/move-concurrency-to-workflow-level
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
  postBuild:
    substitute:
      flux_environment: move-concurrency-to-workflow-level
  images:
    - name: ghcr.io/arikkfir/greenstar/backend
      newTag: 2d0966735518d08093b20acd13e3b395cea0a944
    - name: ghcr.io/arikkfir/greenstar/frontend
      newTag: 2d0966735518d08093b20acd13e3b395cea0a944
    - name: ghcr.io/arikkfir/greenstar/migrations
      newTag: 2d0966735518d08093b20acd13e3b395cea0a944
    - name: ghcr.io/arikkfir/greenstar/neo4j
      newTag: 2d0966735518d08093b20acd13e3b395cea0a944
