apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: env-provide-http-cors-allowed-origins-to-backend
  namespace: default
spec:
  dependsOn:
    - name: cert-manager-issuer
    - name: config-connector-manager
    - name: default
    - name: dns
    - name: external-secrets
    - name: traefik
  interval: 5m
  path: environments/provide-http-cors-allowed-origins-to-backend
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
  postBuild:
    substitute:
      flux_environment: provide-http-cors-allowed-origins-to-backend
  images:
    - name: ghcr.io/arikkfir/greenstar/backend
      newTag: 80161f48be0f0f00e13db4277bde8d7e80847225
    - name: ghcr.io/arikkfir/greenstar/frontend
      newTag: 80161f48be0f0f00e13db4277bde8d7e80847225
    - name: ghcr.io/arikkfir/greenstar/migrations
      newTag: 80161f48be0f0f00e13db4277bde8d7e80847225
    - name: ghcr.io/arikkfir/greenstar/neo4j
      newTag: 80161f48be0f0f00e13db4277bde8d7e80847225
