apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: env-small-gha-refactor
  namespace: default
spec:
  dependsOn:
    - name: cert-manager-issuer
    - name: config-connector-manager
    - name: default
    - name: dns
    - name: external-secrets
    - name: traefik
  interval: 5m
  path: environments/small-gha-refactor
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
  postBuild:
    substitute:
      flux_environment: small-gha-refactor
  images:
    - name: ghcr.io/arikkfir/greenstar/backend
      newTag: 389fa709fddfdbca41b6aff44ae1eac21cffca47
    - name: ghcr.io/arikkfir/greenstar/frontend
      newTag: 389fa709fddfdbca41b6aff44ae1eac21cffca47
    - name: ghcr.io/arikkfir/greenstar/migrations
      newTag: 389fa709fddfdbca41b6aff44ae1eac21cffca47
    - name: ghcr.io/arikkfir/greenstar/neo4j
      newTag: 389fa709fddfdbca41b6aff44ae1eac21cffca47
