apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: e2e-add-graphql
images:
  - name: ghcr.io/arikkfir/greenstar/backend
    newTag: ff1576de7438e925a986f481ce0d2fc5ada755b0
  - name: ghcr.io/arikkfir/greenstar/frontend
    newTag: ff1576de7438e925a986f481ce0d2fc5ada755b0
  - name: ghcr.io/arikkfir/greenstar/migrations
    newTag: ff1576de7438e925a986f481ce0d2fc5ada755b0
  - name: ghcr.io/arikkfir/greenstar/neo4j
    newTag: ff1576de7438e925a986f481ce0d2fc5ada755b0
patches: []
resources:
  - ../main
