apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dependabot-npm-and-yarn-frontend-mui-x-data-grid-premium-6
images:
  - name: ghcr.io/arikkfir/greenstar/backend
    newTag: 81c5330506186228c5616c1b287b662a31357d68
  - name: ghcr.io/arikkfir/greenstar/frontend
    newTag: 81c5330506186228c5616c1b287b662a31357d68
  - name: ghcr.io/arikkfir/greenstar/migrations
    newTag: 81c5330506186228c5616c1b287b662a31357d68
  - name: ghcr.io/arikkfir/greenstar/neo4j
    newTag: 81c5330506186228c5616c1b287b662a31357d68
patches: []
resources:
  - ../main
