apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: secrets-store-csi-driver-provider-gcp
spec:
  displayName: Secrets Store CSI Driver GCP provider
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: secrets-store-csi-driver-provider-gcp-secret-viewer
spec:
  memberFrom:
    serviceAccountRef:
      name: secrets-store-csi-driver-provider-gcp
  role: roles/secretmanager.viewer
  resourceRef:
    kind: Project
    external: projects/arikkfir
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: secrets-store-csi-driver-provider-gcp-secret-accessor
spec:
  memberFrom:
    serviceAccountRef:
      name: secrets-store-csi-driver-provider-gcp
  role: roles/secretmanager.secretAccessor
  resourceRef:
    kind: Project
    external: projects/arikkfir
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: secrets-store-csi-driver-provider-gcp
spec:
  provider: gcp
#  secretObjects:
#    - type: Opaque
#      secretName: k8s secret name
#      data:
#        - key: k8s secret key
#          objectName: gcp secret name
