apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dependabot-npm-and-y-int-8-49-0
images:
  - name: ghcr.io/arikkfir/greenstar/backend
    newTag: db26d79514ccd6a1cf16c76cecb08f405db50b05
  - name: ghcr.io/arikkfir/greenstar/frontend
    newTag: db26d79514ccd6a1cf16c76cecb08f405db50b05
  - name: ghcr.io/arikkfir/greenstar/migrations
    newTag: db26d79514ccd6a1cf16c76cecb08f405db50b05
  - name: ghcr.io/arikkfir/greenstar/neo4j
    newTag: db26d79514ccd6a1cf16c76cecb08f405db50b05
patches: []
resources:
  - ../main
