apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dependabot-npm-and-y-int-8-49-0
images:
  - name: ghcr.io/arikkfir/greenstar/backend
    newTag: 09e513bfdadc526612d532b522162827d4ad486b
  - name: ghcr.io/arikkfir/greenstar/frontend
    newTag: 09e513bfdadc526612d532b522162827d4ad486b
  - name: ghcr.io/arikkfir/greenstar/migrations
    newTag: 09e513bfdadc526612d532b522162827d4ad486b
  - name: ghcr.io/arikkfir/greenstar/neo4j
    newTag: 09e513bfdadc526612d532b522162827d4ad486b
patches:
  - patch: |
      - op: replace
        path: /spec/replicas
        value: 0
    target:
      group: apps
      version: v1
      kind: Deployment
  - patch: |
      - op: replace
        path: /spec/values/replicaCount
        value: 0
    target:
      group: helm.toolkit.fluxcd.io
      version: v2beta1
      kind: HelmRelease
  - patch: |
      - op: replace
        path: /spec/replicas
        value: 0
    target:
      group: apps
      version: v1
      kind: StatefulSet
resources:
  - ../main
