apiVersion: v1
kind: Service
metadata:
  name: neo4j
spec:
  ports:
    - name: client-nontls
      port: 7687
      protocol: TCP
      targetPort: client-nontls
    - name: http
      port: 7474
      protocol: TCP
      targetPort: http
  type: ClusterIP
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: neo4j-tls
spec:
  entryPoints: [ bolt ]
  routes:
    - match: HostSNI(`neo4j.${flux_environment}.greenstar.kfirs.com`)
      middlewares:
        - name: ip-whitelist-tcp
          namespace: traefik
      priority: 999 # TODO: do we need priority here? does it conflict with non-TCP ingress?
      services:
        - name: neo4j
          port: client-nontls
  tls:
    secretName: greenstar-wildcard-tls
