apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 5m
  timeout: 1h
  chart:
    spec:
      chart: cert-manager
      version: 1.x
      sourceRef:
        kind: HelmRepository
        name: jetstack
  valuesFrom:
    - kind: ConfigMap
      name: cert-manager-values
      optional: false

  # This prevents "reconciliation failed: install retries exhausted" errors
  install:
    disableWait: true
  upgrade:
    disableWait: true
