apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 5m
  timeout: 1h
  chart:
    spec:
      chart: cert-manager
      version: 1.x
      sourceRef:
        kind: HelmRepository
        name: jetstack
  values:
    global:
      leaderElection:
        namespace: cert-manager # default is "kube-system" which seems to prevent status checks from working
    nodeSelector:
      node.kfirs.com/role: work
    tolerations:
      - effect: NoExecute
        key: node.kfirs.com/role
        operator: Equal
        value: work
    installCRDs: true
    serviceAccount:
      annotations:
        iam.gke.io/gcp-service-account: cert-manager@arik-kfir.iam.gserviceaccount.com
    resources:
      requests:
        cpu: 100m
        memory: 50Mi
      limits:
        cpu: 100m
        memory: 50Mi
    prometheus:
      enabled: true
      servicemonitor:
        enabled: false
    webhook:
      resources:
        requests:
          cpu: 50m
          memory: 50Mi
        limits:
          cpu: 50m
          memory: 50Mi
      serviceAccount:
        annotations:
          iam.gke.io/gcp-service-account: cert-manager@arik-kfir.iam.gserviceaccount.com
      nodeSelector:
        node.kfirs.com/role: work
      tolerations:
        - effect: NoExecute
          key: node.kfirs.com/role
          operator: Equal
          value: work
    cainjector:
      resources:
        requests:
          cpu: 100m
          memory: 100Mi
        limits:
          cpu: 100m
          memory: 150Mi
      serviceAccount:
        annotations:
          iam.gke.io/gcp-service-account: cert-manager@arik-kfir.iam.gserviceaccount.com
      nodeSelector:
        node.kfirs.com/role: work
      tolerations:
        - effect: NoExecute
          key: node.kfirs.com/role
          operator: Equal
          value: work
    startupapicheck:
      resources:
        requests:
          cpu: 100m
          memory: 50Mi
        limits:
          cpu: 100m
          memory: 50Mi
      serviceAccount:
        annotations:
          iam.gke.io/gcp-service-account: cert-manager@arik-kfir.iam.gserviceaccount.com
      nodeSelector:
        node.kfirs.com/role: work
      tolerations:
        - effect: NoExecute
          key: node.kfirs.com/role
          operator: Equal
          value: work

  # This prevents "reconciliation failed: install retries exhausted" errors
  install:
    disableWait: true
  upgrade:
    disableWait: true
