name: Deploy to Environment

on:
  workflow_call:
    inputs:
      branch:
        type: string
        description: |
          Source branch being deployed to this environment. This will be used, after being "slugged", to infer the
          target environment to deploy the list of images provided in the `images` input.
        required: true
      images:
        type: string
        description: |
          Map of images to deploy, in YAML format of "image: tag" pairs, for example:
          
          ```
          my-image: newTag
          my-2nd-image: new2ndTag
          ```
          
          This MUST be a valid YAML object - thus the space after the `:` character is crucial.
        required: true

defaults:
  run:
    shell: bash -exuo pipefail {0}

env:
  FLUXCD_VERSION: 2.1.0
  GCP_CLI_VERSION: 443.0.0
  GCP_SERVICE_ACCOUNT: delivery@arikkfir.iam.gserviceaccount.com
  GCP_WORKLOAD_IDENTITY_PROVIDER: projects/8909046976/locations/global/workloadIdentityPools/github-actions/providers/github-oidc
  GKE_CLUSTER_NAME: main
  GKE_CLUSTER_LOCATION: me-west1-a

jobs:

  slug:
    name: "Slug"
    runs-on: ubuntu-22.04
    outputs:
      slug: ${{ steps.slug.outputs.slug }}
    steps:
      - id: slug
        run: |
          SLUG=$(echo -n "${{ inputs.branch }}" | sed -E 's/[^a-zA-Z0-9_]+/-/g' | sed -E 's/^-|-$//g' | tr '[:upper:]' '[:lower:]')
          echo "slug=${SLUG}" >> "$GITHUB_OUTPUT"

  deploy:
    name: Deploy images to environment
    needs: slug
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    environment: ${{ needs.slug.outputs.slug }}
    steps:
      - uses: actions/checkout@v3
        with:
          repository: arikkfir/delivery
          token: ${{ secrets.ARIKKFIR_GHA_AUTOMATION }}
      - name: Create environment
        run: |
          if [[ ! -f "clusters/main/environments/${ENVIRONMENT}.yaml" ]]; then
            cat > clusters/main/environments/${ENVIRONMENT}.yaml <<EOF
          apiVersion: kustomize.toolkit.fluxcd.io/v1
          kind: Kustomization
          metadata:
            name: env-${ENVIRONMENT}
            namespace: default
          spec:
            dependsOn:
              - name: cert-manager-issuer
              - name: config-connector-manager
              - name: default
              - name: dns
              - name: external-secrets
              - name: traefik
            interval: 5m
            path: environments/${ENVIRONMENT}
            prune: true
            sourceRef:
              kind: GitRepository
              name: flux-system
              namespace: flux-system
            wait: true
            postBuild:
              substitute:
                flux_environment: ${ENVIRONMENT}
          EOF
          fi
          if [[ ! -f "environments/${ENVIRONMENT}/kustomization.yaml" ]]; then
            mkdir -p environments/${ENVIRONMENT}
            cat > environments/${ENVIRONMENT}/kustomization.yaml <<EOF
          apiVersion: kustomize.config.k8s.io/v1beta1
          kind: Kustomization
          namespace: ${ENVIRONMENT}
          resources:
            - ../_commons/namespace.yaml
            - ../_commons/echo-server.yaml
            - https://github.com/arikkfir/greenstar//deploy/cluster?ref=${BRANCH}
          EOF
          fi
          cat > new-images.yaml <<EOF
          ${{ inputs.images }}
          EOF
          yq e '.spec.images[] | {.name: .newTag}' "clusters/main/environments/${ENVIRONMENT}.yaml" > current-images.yaml
          yq e '. *= load("new-images.yaml") | to_entries | .[] | [{"name":.key,"newTag":.value}]' current-images.yaml > final-images.yaml
          yq e -i '.spec.images=load("final-images.yaml")' "clusters/main/environments/${ENVIRONMENT}.yaml"
          rm -vf current-images.yaml final-images.yaml new-images.yaml
        env:
          BRANCH: ${{ inputs.branch }}
          ENVIRONMENT: ${{ needs.slug.outputs.slug }}
      - uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Actions
          author_email: <gha@kfirs.com>
          message: |-
            Deployment to "${{ needs.slug.outputs.slug }}" from "${{ github.repository }}" 
            
            Environment:       ${{ needs.slug.outputs.slug }}
            Source repository: ${{ github.repository }}
            Branch:            ${{ inputs.branch }}

  verify-env-is-up:
    name: Wait for environment to be up
    needs: [slug, deploy]
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
    environment: ${{ needs.slug.outputs.slug }}
    steps:
      - uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ env.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.GCP_SERVICE_ACCOUNT }}
      - uses: google-github-actions/setup-gcloud@v1
        with:
          install_components: gke-gcloud-auth-plugin
          version: ${{ env.GCP_CLI_VERSION }}
      - uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: ${{ env.GKE_CLUSTER_NAME }}
          location: ${{ env.GKE_CLUSTER_LOCATION }}
      - uses: fluxcd/flux2/action@main
        with:
          version: ${{ env.FLUXCD_VERSION }}
      - run: flux reconcile -n default kustomization env-${ENVIRONMENT}
        env:
          ENVIRONMENT: ${{ needs.slug.outputs.slug }}
