name: Environments Garbage Collection
on:
  workflow_dispatch:
  schedule:
    - cron: 0 * * * *
  push:
    branches:
      - main
    paths:
      - .github/workflows/gc-stale-environments.yml
      - environments/**

defaults:
  run:
    shell: bash -exuo pipefail {0}

concurrency:
  group: production
  cancel-in-progress: false

jobs:
  gc:
    name: Garbage Collect
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - working-directory: environments
        run: |
          for env in $(ls|grep -vE '^main$'); do
            K_FILE="${env}/kustomization.yaml"
            if [[ -f "${K_FILE}" ]]; then
          
              # Ensure the "patches" property exists in the file
              [[ "$(yq e '.patches == null' "${K_FILE}")" == "false" ]] || yq e -i '.patches = []' "${K_FILE}"
          
              # Check whether any updates to the environment file were made recently (if not it is considered stale)
              git log -1 --format=oneline --since="1 hours ago" -- "${env}" | grep -v "chore: garbage collect stale environments" | tee changes.txt
              if [[ "$(cat changes.txt | wc -l | tr -d ' ')" == "0" ]]; then
                # Remove known stale-environments patches & re-add them to the kustomization patches list
                # This is meant to ensure that all known patches are there (for stale environments)
                yq e -i 'load("../etc/stale-env-patches.yaml") ref $p | .patches -= $p | .patches += $p' "${K_FILE}"
              else
                # Remove known stale-environments patches from the kustomization patches list
                # This is meant to ensure that all known patches are not there (for non-stale environments) - this might
                # be needed if the environment was stale in the past and the deployment failed somehow to take it out of
                # the stale state.
                yq e -i 'load("../etc/stale-env-patches.yaml") ref $p | .patches -= $p' "${K_FILE}"
              fi
          
              # Cleanup so it doesn't get added to VCS
              rm -f changes.txt
            fi
          done
      - id: commit
        uses: EndBug/add-and-commit@v9
        with:
          add: environments/*/kustomization.yaml
          author_name: GitHub Actions
          author_email: <delivery@kfirs.com>
          message: 'chore: garbage collect stale environments'
