name: Sync GKE cluster info

on:
  workflow_call:
    inputs:
      gke_cluster_name:
        type: string
        description: GKE cluster name
        required: true
      gke_cluster_location:
        type: string
        description: GKE cluster location (can be region or zone, depending on cluster type)
        required: true
      gke_ingress_region:
        type: string
        description: GKE ingress region (used for specifying the region for the GKE reserved IP address)
        required: true
  workflow_dispatch:
    inputs:
      gke_cluster_name:
        type: string
        description: GKE cluster name
        required: true
      gke_cluster_location:
        type: string
        description: GKE cluster location (can be region or zone, depending on cluster type)
        required: true
      gke_ingress_region:
        type: string
        description: GKE ingress region (used for specifying the region for the GKE reserved IP address)
        required: true

defaults:
  run:
    shell: bash -exuo pipefail {0}

jobs:

  sync-gke-cluster-info:
    name: Sync GKE cluster info
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          repository: arikkfir/delivery
          token: ${{ secrets.ARIKKFIR_DELIVERY_SYNC }}
      - run: |-
          for f in .github/workflows/deploy-to-environment.yml .github/workflows/sync-traefik-lb-address.yml; do
            yq e -P -i '.env.GKE_CLUSTER_NAME=env(GKE_CLUSTER_NAME)' "${f}"
            yq e -P -i '.env.GKE_CLUSTER_LOCATION=env(GKE_CLUSTER_LOCATION)' "${f}"
          done
          yq e -P -i 'select(.kind=="SecretStore").spec.provider.gcpsm.auth.workloadIdentity.clusterLocation|=env(GKE_CLUSTER_LOCATION)' platform/flux-webhook/webhook-secret.yaml
          yq e -P -i 'select(.kind=="SecretStore").spec.provider.gcpsm.auth.workloadIdentity.clusterName|=env(GKE_CLUSTER_NAME)' platform/flux-webhook/webhook-secret.yaml
          yq e -P -i 'select(.kind=="ComputeAddress").spec.location|=env(GKE_INGRESS_REGION)' platform/traefik/gcp-ingress.yaml
        env:
          GKE_CLUSTER_NAME: ${{ inputs.gke_cluster_name }}
          GKE_CLUSTER_LOCATION: ${{ inputs.gke_cluster_location }}
          GKE_INGRESS_REGION: ${{ inputs.gke_ingress_region }}
      - uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Actions
          author_email: <delivery@kfirs.com>
          message: Sync GKE cluster info in workflows
