name: Sync GKE cluster info

on:
  workflow_call:
    inputs:
      gke_cluster_name:
        type: string
        description: GKE cluster name
        required: true
      gke_cluster_location:
        type: string
        description: GKE cluster location (can be region or zone, depending on cluster type)
        required: true
      gke_ingress_region:
        type: string
        description: GKE ingress region (used for specifying the region for the GKE reserved IP address)
        required: true
  workflow_dispatch:
    inputs:
      gke_cluster_name:
        type: string
        description: GKE cluster name
        required: true
      gke_cluster_location:
        type: string
        description: GKE cluster location (can be region or zone, depending on cluster type)
        required: true
      gke_ingress_region:
        type: string
        description: GKE ingress region (used for specifying the region for the GKE reserved IP address)
        required: true

defaults:
  run:
    shell: bash -exuo pipefail {0}

jobs:

  sync-gke-cluster-info:
    name: Sync GKE cluster info
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          repository: arikkfir/delivery
          token: ${{ secrets.SYNC_GKE_CLUSTER_INFO_PAT }}
      - run: |-
          yq e -P -i '.env.GKE_CLUSTER_NAME=env(GKE_CLUSTER_NAME)' .github/workflows/sync-traefik-lb-address.yml
          yq e -P -i '.env.GKE_CLUSTER_LOCATION=env(GKE_CLUSTER_LOCATION)' .github/workflows/sync-traefik-lb-address.yml
          yq e -P -i 'select(.kind=="SecretStore").spec.provider.gcpsm.auth.workloadIdentity.clusterLocation|=env(GKE_CLUSTER_LOCATION)' platform/flux-webhook/webhook-secret.yaml
          yq e -P -i 'select(.kind=="SecretStore").spec.provider.gcpsm.auth.workloadIdentity.clusterName|=env(GKE_CLUSTER_NAME)' platform/flux-webhook/webhook-secret.yaml
          yq e -P -i 'select(.kind=="ComputeAddress").spec.location|=env(GKE_INGRESS_REGION)' platform/traefik/gcp-ingress.yaml
        env:
          GKE_CLUSTER_NAME: ${{ inputs.gke_cluster_name }}
          GKE_CLUSTER_LOCATION: ${{ inputs.gke_cluster_location }}
          GKE_INGRESS_REGION: ${{ inputs.gke_ingress_region }}
      - uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Actions
          author_email: <delivery@kfirs.com>
          message: Sync GKE cluster info in workflows

  apply-fluxcd:
    name: Apply FluxCD
    needs: sync-gke-cluster-info
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    permissions:
      id-token: write
    env:
      FLUXCD_VERSION: 2.1.0
      GCP_SERVICE_ACCOUNT: delivery@arikkfir.iam.gserviceaccount.com
      GCP_WORKLOAD_IDENTITY_PROVIDER: projects/8909046976/locations/global/workloadIdentityPools/github-actions/providers/github-oidc
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ env.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.GCP_SERVICE_ACCOUNT }}
      - uses: google-github-actions/setup-gcloud@v1
        with:
          version: ${{ env.GCP_CLI_VERSION }}
      - uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: ${{ inputs.gke_cluster_name }}
          location: ${{ inputs.gke_cluster_location }}
      - uses: fluxcd/flux2/action@main
        with:
          version: ${{ env.FLUXCD_VERSION }}
      - run: |
          flux bootstrap github \
            --interval 5m \
            --owner arikkfir \
            --repository delivery \
            --read-write-key \
            --branch main \
            --path clusters/${GKE_CLUSTER_NAME} \
            --reconcile \
            --author-email flux@kfirs.com \
            --author-name "FluxCD Bot" \
            --timeout 30m \
            --version=v${FLUXCD_VERSION}
        env:
          GITHUB_TOKEN: ${{ secrets.FLUXCD_PAT }}
          GKE_CLUSTER_NAME: ${{ inputs.gke_cluster_name }}
