name: Sync GKE cluster info

on:
  workflow_call:
    inputs:
      gke_cluster_name:
        type: string
        description: GKE cluster name
        required: true
      gke_cluster_location:
        type: string
        description: GKE cluster location (can be region or zone, depending on cluster type)
        required: true
      gke_ingress_region:
        type: string
        description: GKE ingress region (used for specifying the region for the GKE reserved IP address)
        required: true
  workflow_dispatch:
    inputs:
      gke_cluster_name:
        type: string
        description: GKE cluster name
        required: true
      gke_cluster_location:
        type: string
        description: GKE cluster location (can be region or zone, depending on cluster type)
        required: true
      gke_ingress_region:
        type: string
        description: GKE ingress region (used for specifying the region for the GKE reserved IP address)
        required: true

defaults:
  run:
    shell: bash -exuo pipefail {0}

jobs:

  sync-gke-cluster-info:
    name: Sync GKE cluster info
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    env:
      GKE_CLUSTER_NAME: ${{ inputs.gke_cluster_name }}
      GKE_CLUSTER_LOCATION: ${{ inputs.gke_cluster_location }}
      GKE_INGRESS_REGION: ${{ inputs.gke_ingress_region }}
    steps:
      - uses: actions/checkout@v3
        with:
          repository: arikkfir/delivery
          token: ${{ secrets.ARIKKFIR_DELIVERY_SYNC }}
      - working-directory: .github/workflows
        run: |-
          for f in deploy-to-environment.yml sync-traefik-lb-address.yml undeploy-from-environment.yml; do
            yq e -P -i '.env.GKE_CLUSTER_NAME=env(GKE_CLUSTER_NAME)' "${f}"
            yq e -P -i '.env.GKE_CLUSTER_LOCATION=env(GKE_CLUSTER_LOCATION)' "${f}"
          done
      - working-directory: platform
        run: |-
          yq e -P -i 'select(.kind=="ClusterSecretStore").spec.provider.gcpsm.auth.workloadIdentity.clusterLocation|=env(GKE_CLUSTER_LOCATION)' external-secrets/gcp-iam.yaml
          yq e -P -i 'select(.kind=="ClusterSecretStore").spec.provider.gcpsm.auth.workloadIdentity.clusterName|=env(GKE_CLUSTER_NAME)' external-secrets/gcp-iam.yaml
          yq e -P -i 'select(.kind=="ComputeAddress").spec.location|=env(GKE_INGRESS_REGION)' traefik/gcp-ingress.yaml
      - uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Actions
          author_email: <delivery@kfirs.com>
          message: |
            Sync GKE cluster info in workflows
            
            Cluster name:     ${{ inputs.gke_cluster_name }}
            Cluster location: ${{ inputs.gke_cluster_location }}
            Ingress region:   ${{ inputs.gke_ingress_region }}
