name: Sync Traefik LoadBalancer IP address
on:
  workflow_dispatch:
    inputs:
      home_ip:
        description: Home IP address
        required: false
  schedule:
    - cron: 0 * * * *
  push:
    branches:
      - main
    paths:
      - .github/workflows/sync-traefik-lb-address.yml
defaults:
  run:
    shell: bash -exuo pipefail {0}
env:
  DEFAULT_HOME_IP: 85.64.221.247
  FLUXCD_VERSION: 2.1.0
  GCP_SERVICE_ACCOUNT: delivery@arikkfir.iam.gserviceaccount.com
  GCP_WORKLOAD_IDENTITY_PROVIDER: projects/8909046976/locations/global/workloadIdentityPools/github-actions/providers/github-oidc
  GKE_CLUSTER_NAME: main
  GKE_CLUSTER_LOCATION: me-west1-a
concurrency:
  group: production
  cancel-in-progress: false
jobs:
  sync-traefik-lb:
    name: Sync Traefik LoadBalancer
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.ARIKKFIR_GHA_AUTOMATION }} # required since we're (potentially) modifying a workflow file
      - uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ env.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.GCP_SERVICE_ACCOUNT }}
      - uses: google-github-actions/setup-gcloud@v1
        with:
          skip_install: true
      - uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: ${{ env.GKE_CLUSTER_NAME }}
          location: ${{ env.GKE_CLUSTER_LOCATION }}
      - run: kubectl wait -n traefik --for=condition=Ready ComputeAddress/gke-ingress --timeout=5m
      - id: ip
        run: |
          echo "gke_ingress_ip=$(kubectl get -n traefik ComputeAddress/gke-ingress -ojsonpath='{.spec.address}')" >> "$GITHUB_OUTPUT"
          echo "github_whitelist=$(curl -sSL https://api.github.com/meta | jq '.hooks' | yq 'filter(. != "*::*") + env(HOME_IP)')" >> "$GITHUB_OUTPUT"
        env:
          HOME_IP: ${{ format( '["{0}"]', inputs.home_ip || env.DEFAULT_HOME_IP ) }}
      - run: |-
          yq e -P -i '.env.DEFAULT_HOME_IP=env(HOME_IP)' .github/workflows/sync-traefik-lb-address.yml
          yq e -P -i '.spec.values.service.spec.loadBalancerIP=env(TRAEFIK_IP)' platform/traefik/helm-release.yaml
          yq e -P -i '.spec.values.extraObjects[0].spec.ipWhiteList.sourceRange=env(WHITELIST)' platform/traefik/helm-release.yaml
          yq e -P -i '.spec.values.extraObjects[1].spec.ipWhiteList.sourceRange=env(WHITELIST)' platform/traefik/helm-release.yaml
        env:
          HOME_IP: ${{ inputs.home_ip || env.DEFAULT_HOME_IP }}
          TRAEFIK_IP: ${{ steps.ip.outputs.gke_ingress_ip }}
          WHITELIST: ${{ steps.ip.outputs.github_whitelist }}
      - id: commit
        uses: EndBug/add-and-commit@v9
        with:
          add: .github/workflows/sync-traefik-lb-address.yml platform/traefik/helm-release.yaml
          author_name: GitHub Actions
          author_email: <delivery@kfirs.com>
          message: |
            chore: sync GKE ingress IP & whitelists

            [skip ci]
      - uses: fluxcd/flux2/action@main
        if: steps.commit.outputs.pushed == 'true'
        with:
          version: ${{ env.FLUXCD_VERSION }}
      - if: steps.commit.outputs.pushed == 'true'
        run: |
          # Reconcile the Git repository
          kubectl annotate --field-manager=flux-client-side-apply -n flux-system --overwrite gitrepository/flux-system reconcile.fluxcd.io/requestedAt="$(date +%s)"
          kubectl wait -n flux-system gitrepository/flux-system --for=condition=ready=True --timeout=10m
          
          # Reconcile the Flux CD kustomization
          kubectl annotate --field-manager=flux-client-side-apply -n flux-system --overwrite kustomization/flux-system reconcile.fluxcd.io/requestedAt="$(date +%s)"
          kubectl wait -n flux-system kustomization/flux-system --for=condition=ready=True --timeout=30m
          
          # Reconcile the environment kustomization
          kubectl annotate --field-manager=flux-client-side-apply -n default --overwrite kustomization/traefik reconcile.fluxcd.io/requestedAt="$(date +%s)"
          kubectl wait -n default kustomization/traefik --for=condition=ready=True --timeout=30m
