name: Sync Traefik LoadBalancer IP address
on:
  workflow_dispatch:
  schedule:
    - cron: 0 * * * *
  push:
    branches:
      - main
    paths:
      - .github/workflows/sync-traefik-lb-address.yml
defaults:
  run:
    shell: bash -exuo pipefail {0}
env:
  GCP_CLI_VERSION: 443.0.0
  GCP_SERVICE_ACCOUNT: delivery@arikkfir.iam.gserviceaccount.com
  GCP_WORKLOAD_IDENTITY_PROVIDER: projects/8909046976/locations/global/workloadIdentityPools/github-actions/providers/github-oidc
  GKE_CLUSTER_NAME: main
  GKE_CLUSTER_LOCATION: me-west1-a
concurrency:
  group: production
  cancel-in-progress: false
jobs:
  sync-traefik-lb:
    name: Sync Traefik LoadBalancer
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ env.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.GCP_SERVICE_ACCOUNT }}
      - uses: google-github-actions/setup-gcloud@v1
        with:
          install_components: gke-gcloud-auth-plugin
          version: ${{ env.GCP_CLI_VERSION }}
      - uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: ${{ env.GKE_CLUSTER_NAME }}
          location: ${{ env.GKE_CLUSTER_LOCATION }}
      - run: kubectl wait -n traefik --for=condition=Ready ComputeAddress/gke-ingress --timeout=5m
      - id: ip
        run: |
          echo "gke_ingress_ip=$(kubectl get -n traefik ComputeAddress/gke-ingress -ojsonpath='{.spec.address}')" >> "$GITHUB_OUTPUT"
          echo "github_whitelist=$(curl -sSL https://api.github.com/meta | jq '.hooks' | yq 'filter(. != "*::*") + env(STATIC_IP_WHITELIST)')" >> "$GITHUB_OUTPUT"
        env:
          STATIC_IP_WHITELIST: '["109.253.161.115/32"]'
      - run: |-
          yq e -P -i '.spec.values.service.spec.loadBalancerIP=env(TRAEFIK_IP)' platform/traefik/helm-release.yaml
          yq e -P -i '.spec.values.extraObjects[0].spec.ipWhiteList.sourceRange=env(WHITELIST)' platform/traefik/helm-release.yaml
          yq e -P -i '.spec.values.extraObjects[1].spec.ipWhiteList.sourceRange=env(WHITELIST)' platform/traefik/helm-release.yaml
        env:
          TRAEFIK_IP: ${{ steps.ip.outputs.gke_ingress_ip }}
          WHITELIST: ${{ steps.ip.outputs.github_whitelist }}
      - uses: EndBug/add-and-commit@v9
        with:
          add: platform/traefik
          author_name: GitHub Actions
          author_email: <delivery@kfirs.com>
          message: Sync GKE Ingress IP & Whitelists
