name: Test

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/test.yml

defaults:
  run:
    shell: bash -exuo pipefail {0}

jobs:

  test:
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: projects/8909046976/locations/global/workloadIdentityPools/github-actions/providers/github-oidc
          service_account: delivery@arikkfir.iam.gserviceaccount.com
      - uses: google-github-actions/setup-gcloud@v1
        with:
#          install_components: gke-gcloud-auth-plugin
          skip_install: true
#          version: 443.0.0
      - uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: main
          location: me-west1-a
      - run: kubectl get ns
