name: Delete from Environment
on:
  workflow_call:
    inputs:
      branch:
        type: string
        description: |
          Source branch for which a PR was closed in another repository. This will be used, after being "slugged", to
          infer the target environment from which the given set of images provided in the `images` input will be
          un-deployed from. If the resulting environment will no longer have any images deployed to it, it will be
          closed entirely.
        required: true
      images:
        type: string
        description: |
          List of image repositories to remove.

          IMPORTANT: this list should only contain the "repository" part of the images - and NOT their tag. For example:

          ```
          my-image
          my-2nd-image
          ```
        required: true
defaults:
  run:
    shell: bash -exuo pipefail {0}
env:
  GKE_CLUSTER_NAME: main
  GKE_CLUSTER_LOCATION: me-west1-a
jobs:
  undeploy:
    name: Undeploy images from environment
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          repository: arikkfir/delivery
          token: ${{ secrets.ARIKKFIR_GHA_AUTOMATION }}
      - uses: arikkfir/delivery-env-name@v1
        id: env
        with:
          branch: ${{ inputs.branch }}
      - run: "# Dump the list of image repositories to a file\ncat > images-to-remove.txt <<EOF\n${{ inputs.images }}\nEOF\necho >> images-to-remove.txt # ensure new-line at the end of the file, required for \"while read\" below\n\n# Remove the images from the kustomization file's list of images\nif [[ -f \"${K_FILE}\" ]]; then\n  while read image; do\n    yq e -i \"del(.spec.images[] | select(.name==\\\"${image}\\\"))\" \"${K_FILE}\"\n  done < images-to-remove.txt\nfi \n\n# If no images left, remove the environment\nif [[ \"$(yq e '.spec.images|length' \"${K_FILE}\")\" == \"0\" ]]; then\n  rm -rfv \"${FLUX_K_FILE}\" \"$(dirname \"${K_FILE}\")\"\nfi\n"
        env:
          FLUX_K_FILE: clusters/${{ env.GKE_CLUSTER_NAME }}/environments/${{ steps.env.outputs.name }}.yaml
          K_FILE: environments/${{ steps.env.outputs.name }}/kustomization.yaml
      - uses: EndBug/add-and-commit@v9
        with:
          add: clusters/${{ env.GKE_CLUSTER_NAME }}/environments/${{ steps.env.outputs.name }}.yaml environments/${{ steps.env.outputs.name }}
          author_name: GitHub Actions
          author_email: <delivery@kfirs.com>
          message: |
            Deleting "${{ needs.slug.outputs.slug }}" (no longer needed)

            Triggering repository:      ${{ github.repository }}
            Triggering branch (closed): ${{ inputs.branch }}
