apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dependabot-npm-and-yarn-frontend-mui-x-data-grid-premium-6-
images:
  - name: ghcr.io/arikkfir/greenstar/backend
    newTag: a28eb24018b5b54d314bb25593ed7efa7431d4db
  - name: ghcr.io/arikkfir/greenstar/frontend
    newTag: a28eb24018b5b54d314bb25593ed7efa7431d4db
  - name: ghcr.io/arikkfir/greenstar/migrations
    newTag: a28eb24018b5b54d314bb25593ed7efa7431d4db
  - name: ghcr.io/arikkfir/greenstar/neo4j
    newTag: a28eb24018b5b54d314bb25593ed7efa7431d4db
patches: []
resources:
  - ../main
