apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dependabot-docker-backend-golang-1-21
images:
  - name: ghcr.io/arikkfir/greenstar/backend
    newTag: a3e47f793af59d1304655e42a878c2079e10d42d
  - name: ghcr.io/arikkfir/greenstar/frontend
    newTag: a3e47f793af59d1304655e42a878c2079e10d42d
  - name: ghcr.io/arikkfir/greenstar/migrations
    newTag: a3e47f793af59d1304655e42a878c2079e10d42d
  - name: ghcr.io/arikkfir/greenstar/neo4j
    newTag: a3e47f793af59d1304655e42a878c2079e10d42d
patches: []
resources:
  - ../main
